// Capital cities keyed by the exact NAME used in our app (after NAME_OVERRIDES).
// Accepted answers are arrays — first entry is canonical, rest are accepted aliases.
export const CAPITALS = {
  // ── Africa ────────────────────────────────────────────────────────────────
  'Algeria':                      ['Algiers'],
  'Angola':                       ['Luanda'],
  'Benin':                        ['Porto-Novo', 'Cotonou'],
  'Botswana':                     ['Gaborone'],
  'Burkina Faso':                 ['Ouagadougou'],
  'Burundi':                      ['Gitega', 'Bujumbura'],
  'Cabo Verde':                   ['Praia'],
  'Cameroon':                     ['Yaoundé', 'Yaounde'],
  'Central African Republic':     ['Bangui'],
  'Chad':                         ['N\'Djamena', 'Ndjamena'],
  'Comoros':                      ['Moroni'],
  'Congo':                        ['Brazzaville'],
  'Democratic Republic of Congo': ['Kinshasa'],
  'Djibouti':                     ['Djibouti'],
  'Egypt':                        ['Cairo'],
  'Equatorial Guinea':            ['Malabo'],
  'Eritrea':                      ['Asmara'],
  'Eswatini':                     ['Mbabane', 'Lobamba'],
  'Ethiopia':                     ['Addis Ababa'],
  'Gabon':                        ['Libreville'],
  'Gambia':                       ['Banjul'],
  'Ghana':                        ['Accra'],
  'Guinea':                       ['Conakry'],
  'Guinea-Bissau':                ['Bissau'],
  'Ivory Coast':                  ['Yamoussoukro', 'Abidjan'],
  'Kenya':                        ['Nairobi'],
  'Lesotho':                      ['Maseru'],
  'Liberia':                      ['Monrovia'],
  'Libya':                        ['Tripoli'],
  'Madagascar':                   ['Antananarivo'],
  'Malawi':                       ['Lilongwe'],
  'Mali':                         ['Bamako'],
  'Mauritania':                   ['Nouakchott'],
  'Mauritius':                    ['Port Louis'],
  'Morocco':                      ['Rabat'],
  'Mozambique':                   ['Maputo'],
  'Namibia':                      ['Windhoek'],
  'Niger':                        ['Niamey'],
  'Nigeria':                      ['Abuja'],
  'Rwanda':                       ['Kigali'],
  'Sao Tome and Principe':        ['São Tomé', 'Sao Tome'],
  'Senegal':                      ['Dakar'],
  'Seychelles':                   ['Victoria'],
  'Sierra Leone':                 ['Freetown'],
  'Somalia':                      ['Mogadishu'],
  'South Africa':                 ['Pretoria', 'Cape Town', 'Bloemfontein'],
  'South Sudan':                  ['Juba'],
  'Sudan':                        ['Khartoum'],
  'Tanzania':                     ['Dodoma', 'Dar es Salaam'],
  'Togo':                         ['Lomé', 'Lome'],
  'Tunisia':                      ['Tunis'],
  'Uganda':                       ['Kampala'],
  'Zambia':                       ['Lusaka'],
  'Zimbabwe':                     ['Harare'],

  // ── Americas ──────────────────────────────────────────────────────────────
  'Antigua and Barbuda':          ['Saint John\'s', 'St. John\'s'],
  'Argentina':                    ['Buenos Aires'],
  'Bahamas':                      ['Nassau'],
  'Barbados':                     ['Bridgetown'],
  'Belize':                       ['Belmopan'],
  'Bolivia':                      ['Sucre', 'La Paz'],
  'Brazil':                       ['Brasília', 'Brasilia'],
  'Canada':                       ['Ottawa'],
  'Chile':                        ['Santiago'],
  'Colombia':                     ['Bogotá', 'Bogota'],
  'Costa Rica':                   ['San José', 'San Jose'],
  'Cuba':                         ['Havana'],
  'Dominica':                     ['Roseau'],
  'Dominican Republic':           ['Santo Domingo'],
  'Ecuador':                      ['Quito'],
  'El Salvador':                  ['San Salvador'],
  'Grenada':                      ['St. George\'s', 'Saint George\'s'],
  'Guatemala':                    ['Guatemala City'],
  'Guyana':                       ['Georgetown'],
  'Haiti':                        ['Port-au-Prince'],
  'Honduras':                     ['Tegucigalpa'],
  'Jamaica':                      ['Kingston'],
  'Mexico':                       ['Mexico City'],
  'Nicaragua':                    ['Managua'],
  'Panama':                       ['Panama City'],
  'Paraguay':                     ['Asunción', 'Asuncion'],
  'Peru':                         ['Lima'],
  'Saint Kitts and Nevis':        ['Basseterre'],
  'Saint Lucia':                  ['Castries'],
  'Saint Vincent and the Grenadines': ['Kingstown'],
  'Suriname':                     ['Paramaribo'],
  'Trinidad and Tobago':          ['Port of Spain'],
  'United States of America':     ['Washington D.C.', 'Washington DC', 'Washington'],
  'Uruguay':                      ['Montevideo'],
  'Venezuela':                    ['Caracas'],

  // ── Asia ──────────────────────────────────────────────────────────────────
  'Afghanistan':                  ['Kabul'],
  'Armenia':                      ['Yerevan'],
  'Azerbaijan':                   ['Baku'],
  'Bahrain':                      ['Manama'],
  'Bangladesh':                   ['Dhaka'],
  'Bhutan':                       ['Thimphu'],
  'Brunei':                       ['Bandar Seri Begawan'],
  'Cambodia':                     ['Phnom Penh'],
  'China':                        ['Beijing'],
  'Cyprus':                       ['Nicosia'],
  'Georgia':                      ['Tbilisi'],
  'India':                        ['New Delhi'],
  'Indonesia':                    ['Jakarta'],
  'Iran':                         ['Tehran'],
  'Iraq':                         ['Baghdad'],
  'Israel':                       ['Jerusalem'],
  'Japan':                        ['Tokyo'],
  'Jordan':                       ['Amman'],
  'Kazakhstan':                   ['Astana', 'Nur-Sultan'],
  'Kuwait':                       ['Kuwait City'],
  'Kyrgyzstan':                   ['Bishkek'],
  'Laos':                         ['Vientiane'],
  'Lebanon':                      ['Beirut'],
  'Malaysia':                     ['Kuala Lumpur'],
  'Maldives':                     ['Malé', 'Male'],
  'Mongolia':                     ['Ulaanbaatar', 'Ulan Bator'],
  'Myanmar':                      ['Naypyidaw', 'Naypyitaw'],
  'Nepal':                        ['Kathmandu'],
  'North Korea':                  ['Pyongyang'],
  'Oman':                         ['Muscat'],
  'Pakistan':                     ['Islamabad'],
  'Palestine':                    ['Ramallah'],
  'Philippines':                  ['Manila'],
  'Qatar':                        ['Doha'],
  'Saudi Arabia':                 ['Riyadh'],
  'Singapore':                    ['Singapore'],
  'South Korea':                  ['Seoul'],
  'Sri Lanka':                    ['Sri Jayawardenepura Kotte', 'Colombo'],
  'Syria':                        ['Damascus'],
  'Taiwan':                       ['Taipei'],
  'Tajikistan':                   ['Dushanbe'],
  'Thailand':                     ['Bangkok'],
  'Timor-Leste':                  ['Dili'],
  'Turkey':                       ['Ankara'],
  'Turkmenistan':                 ['Ashgabat', 'Ashkhabad'],
  'United Arab Emirates':         ['Abu Dhabi'],
  'Uzbekistan':                   ['Tashkent'],
  'Vietnam':                      ['Hanoi'],
  'Yemen':                        ['Sana\'a', 'Sanaa'],

  // ── Europe ────────────────────────────────────────────────────────────────
  'Albania':                      ['Tirana'],
  'Andorra':                      ['Andorra la Vella'],
  'Austria':                      ['Vienna'],
  'Belarus':                      ['Minsk'],
  'Belgium':                      ['Brussels'],
  'Bosnia and Herzegovina':       ['Sarajevo'],
  'Bulgaria':                     ['Sofia'],
  'Croatia':                      ['Zagreb'],
  'Czech Republic':               ['Prague'],
  'Denmark':                      ['Copenhagen'],
  'Estonia':                      ['Tallinn'],
  'Finland':                      ['Helsinki'],
  'France':                       ['Paris'],
  'Germany':                      ['Berlin'],
  'Greece':                       ['Athens'],
  'Hungary':                      ['Budapest'],
  'Iceland':                      ['Reykjavik', 'Reykjavík'],
  'Ireland':                      ['Dublin'],
  'Italy':                        ['Rome'],
  'Kosovo':                       ['Pristina', 'Prishtina'],
  'Latvia':                       ['Riga'],
  'Liechtenstein':                ['Vaduz'],
  'Lithuania':                    ['Vilnius'],
  'Luxembourg':                   ['Luxembourg'],
  'Malta':                        ['Valletta'],
  'Moldova':                      ['Chișinău', 'Chisinau'],
  'Monaco':                       ['Monaco'],
  'Montenegro':                   ['Podgorica'],
  'Netherlands':                  ['Amsterdam', 'The Hague'],
  'North Macedonia':              ['Skopje'],
  'Norway':                       ['Oslo'],
  'Poland':                       ['Warsaw'],
  'Portugal':                     ['Lisbon'],
  'Romania':                      ['Bucharest'],
  'Russia':                       ['Moscow'],
  'San Marino':                   ['San Marino'],
  'Serbia':                       ['Belgrade'],
  'Slovakia':                     ['Bratislava'],
  'Slovenia':                     ['Ljubljana'],
  'Spain':                        ['Madrid'],
  'Sweden':                       ['Stockholm'],
  'Switzerland':                  ['Bern'],
  'Ukraine':                      ['Kyiv', 'Kiev'],
  'United Kingdom':               ['London'],
  'Vatican':                      ['Vatican City'],

  // ── Oceania ───────────────────────────────────────────────────────────────
  'Australia':                    ['Canberra'],
  'Fiji':                         ['Suva'],
  'Kiribati':                     ['South Tarawa', 'Tarawa'],
  'Marshall Islands':             ['Majuro'],
  'Federated States of Micronesia': ['Palikir'],
  'Nauru':                        ['Yaren'],
  'New Zealand':                  ['Wellington'],
  'Palau':                        ['Ngerulmud'],
  'Papua New Guinea':             ['Port Moresby'],
  'Samoa':                        ['Apia'],
  'Solomon Islands':              ['Honiara'],
  'Tonga':                        ['Nuku\'alofa', 'Nukualofa'],
  'Tuvalu':                       ['Funafuti'],
  'Vanuatu':                      ['Port Vila'],
}

// Normalize a string for loose comparison
export function normalizeCapital(s) {
  return s.toLowerCase().trim()
    .replace(/[''`]/g, "'")
    .replace(/\s+/g, ' ')
}

// Check if a typed answer matches any accepted form of the capital
export function checkCapital(countryName, typed) {
  const accepted = CAPITALS[countryName]
  if (!accepted) return false
  const t = normalizeCapital(typed)
  return accepted.some(a => normalizeCapital(a) === t)
}
