// Official and widely spoken languages per country
// Format: [official, second?, third?]
// Keyed by post-NAME_OVERRIDE country names
export const COUNTRY_LANGUAGES = {
  'Afghanistan':                       ['Dari', 'Pashto'],
  'Albania':                           ['Albanian'],
  'Algeria':                           ['Arabic', 'Tamazight', 'French'],
  'Andorra':                           ['Catalan', 'Spanish', 'French'],
  'Angola':                            ['Portuguese', 'Umbundu', 'Kikongo'],
  'Antigua and Barbuda':               ['English'],
  'Argentina':                         ['Spanish'],
  'Armenia':                           ['Armenian'],
  'Australia':                         ['English'],
  'Austria':                           ['German'],
  'Azerbaijan':                        ['Azerbaijani', 'Russian'],
  'Bahamas':                           ['English'],
  'Bahrain':                           ['Arabic'],
  'Bangladesh':                        ['Bengali'],
  'Barbados':                          ['English'],
  'Belarus':                           ['Belarusian', 'Russian'],
  'Belgium':                           ['Dutch', 'French', 'German'],
  'Belize':                            ['English', 'Spanish', 'Kriol'],
  'Benin':                             ['French', 'Fon', 'Yoruba'],
  'Bhutan':                            ['Dzongkha'],
  'Bolivia':                           ['Spanish', 'Quechua', 'Aymara'],
  'Bosnia and Herzegovina':            ['Bosnian', 'Croatian', 'Serbian'],
  'Botswana':                          ['English', 'Tswana'],
  'Brazil':                            ['Portuguese'],
  'Brunei':                            ['Malay', 'English'],
  'Bulgaria':                          ['Bulgarian'],
  'Burkina Faso':                      ['French', 'Mooré', 'Dyula'],
  'Burundi':                           ['Kirundi', 'French', 'Swahili'],
  'Cabo Verde':                        ['Portuguese', 'Cape Verdean Creole'],
  'Cambodia':                          ['Khmer'],
  'Cameroon':                          ['French', 'English'],
  'Canada':                            ['English', 'French'],
  'Central African Republic':          ['Sango', 'French'],
  'Chad':                              ['French', 'Arabic'],
  'Chile':                             ['Spanish'],
  'China':                             ['Mandarin'],
  'Colombia':                          ['Spanish'],
  'Comoros':                           ['Comorian', 'Arabic', 'French'],
  'Costa Rica':                        ['Spanish'],
  'Croatia':                           ['Croatian'],
  'Cuba':                              ['Spanish'],
  'Cyprus':                            ['Greek', 'Turkish'],
  'Czechia':                           ['Czech'],
  'Democratic Republic of Congo':      ['French', 'Lingala', 'Swahili'],
  'Denmark':                           ['Danish'],
  'Djibouti':                          ['Arabic', 'French', 'Somali'],
  'Dominica':                          ['English'],
  'Dominican Republic':                ['Spanish'],
  'Ecuador':                           ['Spanish', 'Quechua'],
  'Egypt':                             ['Arabic'],
  'El Salvador':                       ['Spanish'],
  'Equatorial Guinea':                 ['Spanish', 'French', 'Portuguese'],
  'Eritrea':                           ['Tigrinya', 'Arabic', 'English'],
  'Estonia':                           ['Estonian'],
  'Eswatini':                          ['Swati', 'English'],
  'Ethiopia':                          ['Amharic', 'Oromo', 'Somali'],
  'Federated States of Micronesia':    ['English', 'Chuukese'],
  'Fiji':                              ['English', 'Fijian', 'Hindi'],
  'Finland':                           ['Finnish', 'Swedish'],
  'France':                            ['French'],
  'Gabon':                             ['French', 'Fang'],
  'Gambia':                            ['English', 'Mandinka'],
  'Georgia':                           ['Georgian'],
  'Germany':                           ['German'],
  'Ghana':                             ['English', 'Akan', 'Ewe'],
  'Greece':                            ['Greek'],
  'Grenada':                           ['English'],
  'Guatemala':                         ['Spanish', 'Kʼicheʼ', 'Mam'],
  'Guinea':                            ['French', 'Pular', 'Mandinka'],
  'Guinea-Bissau':                     ['Portuguese', 'Creole'],
  'Guyana':                            ['English'],
  'Haiti':                             ['French', 'Haitian Creole'],
  'Honduras':                          ['Spanish'],
  'Hungary':                           ['Hungarian'],
  'Iceland':                           ['Icelandic'],
  'India':                             ['Hindi', 'English', 'Bengali'],
  'Indonesia':                         ['Indonesian', 'Javanese'],
  'Iran':                              ['Persian', 'Azerbaijani', 'Kurdish'],
  'Iraq':                              ['Arabic', 'Kurdish'],
  'Ireland':                           ['English', 'Irish'],
  'Israel':                            ['Hebrew', 'Arabic'],
  'Italy':                             ['Italian'],
  'Ivory Coast':                       ['French', 'Dioula', 'Baoulé'],
  'Jamaica':                           ['English'],
  'Japan':                             ['Japanese'],
  'Jordan':                            ['Arabic'],
  'Kazakhstan':                        ['Kazakh', 'Russian'],
  'Kenya':                             ['Swahili', 'English'],
  'Kiribati':                          ['English', 'Gilbertese'],
  'Kosovo':                            ['Albanian', 'Serbian'],
  'Kuwait':                            ['Arabic'],
  'Kyrgyzstan':                        ['Kyrgyz', 'Russian'],
  'Laos':                              ['Lao'],
  'Latvia':                            ['Latvian'],
  'Lebanon':                           ['Arabic', 'French'],
  'Lesotho':                           ['Sesotho', 'English'],
  'Liberia':                           ['English'],
  'Libya':                             ['Arabic'],
  'Liechtenstein':                     ['German'],
  'Lithuania':                         ['Lithuanian'],
  'Luxembourg':                        ['Luxembourgish', 'French', 'German'],
  'Madagascar':                        ['Malagasy', 'French'],
  'Malawi':                            ['Chichewa', 'English'],
  'Malaysia':                          ['Malay', 'English', 'Chinese'],
  'Maldives':                          ['Dhivehi'],
  'Mali':                              ['French', 'Bambara'],
  'Malta':                             ['Maltese', 'English'],
  'Marshall Islands':                  ['Marshallese', 'English'],
  'Mauritania':                        ['Arabic', 'Hassaniya'],
  'Mauritius':                         ['English', 'French', 'Creole'],
  'Mexico':                            ['Spanish'],
  'Moldova':                           ['Romanian', 'Russian'],
  'Monaco':                            ['French'],
  'Mongolia':                          ['Mongolian'],
  'Montenegro':                        ['Montenegrin', 'Serbian'],
  'Morocco':                           ['Arabic', 'Tamazight', 'French'],
  'Mozambique':                        ['Portuguese', 'Makhuwa', 'Changana'],
  'Myanmar':                           ['Burmese'],
  'Namibia':                           ['English', 'Afrikaans', 'German'],
  'Nauru':                             ['Nauruan', 'English'],
  'Nepal':                             ['Nepali', 'Maithili'],
  'Netherlands':                       ['Dutch'],
  'New Zealand':                       ['English', 'Māori'],
  'Nicaragua':                         ['Spanish'],
  'Niger':                             ['French', 'Hausa', 'Zarma'],
  'Nigeria':                           ['English', 'Hausa', 'Yoruba'],
  'North Korea':                       ['Korean'],
  'North Macedonia':                   ['Macedonian', 'Albanian'],
  'Norway':                            ['Norwegian'],
  'Oman':                              ['Arabic'],
  'Pakistan':                          ['Urdu', 'English', 'Punjabi'],
  'Palau':                             ['Palauan', 'English'],
  'Panama':                            ['Spanish'],
  'Papua New Guinea':                  ['Tok Pisin', 'English', 'Hiri Motu'],
  'Paraguay':                          ['Spanish', 'Guaraní'],
  'Peru':                              ['Spanish', 'Quechua', 'Aymara'],
  'Philippines':                       ['Filipino', 'English'],
  'Poland':                            ['Polish'],
  'Portugal':                          ['Portuguese'],
  'Qatar':                             ['Arabic'],
  'Republic of the Congo':             ['French', 'Lingala', 'Kituba'],
  'Romania':                           ['Romanian'],
  'Russia':                            ['Russian'],
  'Rwanda':                            ['Kinyarwanda', 'French', 'English'],
  'Saint Kitts and Nevis':             ['English'],
  'Saint Lucia':                       ['English'],
  'Saint Vincent and the Grenadines':  ['English'],
  'Samoa':                             ['Samoan', 'English'],
  'San Marino':                        ['Italian'],
  'Saudi Arabia':                      ['Arabic'],
  'Senegal':                           ['French', 'Wolof', 'Pulaar'],
  'Serbia':                            ['Serbian'],
  'Seychelles':                        ['Seychellois Creole', 'English', 'French'],
  'Sierra Leone':                      ['English', 'Krio'],
  'Singapore':                         ['English', 'Malay', 'Mandarin'],
  'Slovakia':                          ['Slovak'],
  'Slovenia':                          ['Slovenian'],
  'Solomon Islands':                   ['English', 'Solomon Islands Pijin'],
  'Somalia':                           ['Somali', 'Arabic'],
  'South Africa':                      ['Zulu', 'Xhosa', 'Afrikaans', 'English'],
  'South Korea':                       ['Korean'],
  'South Sudan':                       ['English', 'Arabic', 'Dinka'],
  'Spain':                             ['Spanish', 'Catalan', 'Basque'],
  'Sri Lanka':                         ['Sinhala', 'Tamil'],
  'Sudan':                             ['Arabic', 'English'],
  'Suriname':                          ['Dutch', 'Sranantongo'],
  'Sweden':                            ['Swedish'],
  'Switzerland':                       ['German', 'French', 'Italian'],
  'Syria':                             ['Arabic', 'Kurdish'],
  'São Tomé and Príncipe':             ['Portuguese'],
  'Taiwan':                            ['Mandarin', 'Taiwanese Hokkien'],
  'Tajikistan':                        ['Tajik', 'Russian'],
  'Tanzania':                          ['Swahili', 'English'],
  'Thailand':                          ['Thai'],
  'Timor-Leste':                       ['Tetum', 'Portuguese'],
  'Togo':                              ['French', 'Ewe', 'Kabiyé'],
  'Tonga':                             ['Tongan', 'English'],
  'Trinidad and Tobago':               ['English'],
  'Tunisia':                           ['Arabic', 'French'],
  'Turkey':                            ['Turkish'],
  'Turkmenistan':                      ['Turkmen', 'Russian'],
  'Tuvalu':                            ['Tuvaluan', 'English'],
  'Uganda':                            ['English', 'Swahili', 'Luganda'],
  'Ukraine':                           ['Ukrainian', 'Russian'],
  'United Arab Emirates':              ['Arabic'],
  'United Kingdom':                    ['English'],
  'United States of America':          ['English', 'Spanish'],
  'Uruguay':                           ['Spanish'],
  'Uzbekistan':                        ['Uzbek', 'Russian'],
  'Vanuatu':                           ['Bislama', 'English', 'French'],
  'Vatican City':                      ['Italian', 'Latin'],
  'Venezuela':                         ['Spanish'],
  'Vietnam':                           ['Vietnamese'],
  'Yemen':                             ['Arabic'],
  'Zambia':                            ['English', 'Bemba', 'Nyanja'],
  'Zimbabwe':                          ['English', 'Shona', 'Ndebele'],
}
