// Official currency for each country, keyed by post-NAME_OVERRIDE names
// Format: { name, symbol, code }
export const COUNTRY_CURRENCY = {
  'Afghanistan':                       { name: 'Afghan Afghani',         symbol: '؋',  code: 'AFN' },
  'Albania':                           { name: 'Albanian Lek',           symbol: 'L',  code: 'ALL' },
  'Algeria':                           { name: 'Algerian Dinar',         symbol: 'د.ج', code: 'DZD' },
  'Andorra':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Angola':                            { name: 'Angolan Kwanza',         symbol: 'Kz', code: 'AOA' },
  'Antigua and Barbuda':               { name: 'East Caribbean Dollar',  symbol: '$',  code: 'XCD' },
  'Argentina':                         { name: 'Argentine Peso',         symbol: '$',  code: 'ARS' },
  'Armenia':                           { name: 'Armenian Dram',          symbol: '֏',  code: 'AMD' },
  'Australia':                         { name: 'Australian Dollar',      symbol: '$',  code: 'AUD' },
  'Austria':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Azerbaijan':                        { name: 'Azerbaijani Manat',      symbol: '₼',  code: 'AZN' },
  'Bahamas':                           { name: 'Bahamian Dollar',        symbol: '$',  code: 'BSD' },
  'Bahrain':                           { name: 'Bahraini Dinar',         symbol: '.د.ب', code: 'BHD' },
  'Bangladesh':                        { name: 'Bangladeshi Taka',       symbol: '৳',  code: 'BDT' },
  'Barbados':                          { name: 'Barbadian Dollar',       symbol: '$',  code: 'BBD' },
  'Belarus':                           { name: 'Belarusian Ruble',       symbol: 'Br', code: 'BYN' },
  'Belgium':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Belize':                            { name: 'Belize Dollar',          symbol: '$',  code: 'BZD' },
  'Benin':                             { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Bhutan':                            { name: 'Bhutanese Ngultrum',     symbol: 'Nu', code: 'BTN' },
  'Bolivia':                           { name: 'Bolivian Boliviano',     symbol: 'Bs', code: 'BOB' },
  'Bosnia and Herzegovina':            { name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', code: 'BAM' },
  'Botswana':                          { name: 'Botswanan Pula',         symbol: 'P',  code: 'BWP' },
  'Brazil':                            { name: 'Brazilian Real',         symbol: 'R$', code: 'BRL' },
  'Brunei':                            { name: 'Brunei Dollar',          symbol: '$',  code: 'BND' },
  'Bulgaria':                          { name: 'Bulgarian Lev',          symbol: 'лв', code: 'BGN' },
  'Burkina Faso':                      { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Burundi':                           { name: 'Burundian Franc',        symbol: 'Fr', code: 'BIF' },
  'Cabo Verde':                        { name: 'Cape Verdean Escudo',    symbol: '$',  code: 'CVE' },
  'Cambodia':                          { name: 'Cambodian Riel',         symbol: '៛',  code: 'KHR' },
  'Cameroon':                          { name: 'Central African CFA Franc', symbol: 'Fr', code: 'XAF' },
  'Canada':                            { name: 'Canadian Dollar',        symbol: '$',  code: 'CAD' },
  'Central African Republic':          { name: 'Central African CFA Franc', symbol: 'Fr', code: 'XAF' },
  'Chad':                              { name: 'Central African CFA Franc', symbol: 'Fr', code: 'XAF' },
  'Chile':                             { name: 'Chilean Peso',           symbol: '$',  code: 'CLP' },
  'China':                             { name: 'Chinese Yuan',           symbol: '¥',  code: 'CNY' },
  'Colombia':                          { name: 'Colombian Peso',         symbol: '$',  code: 'COP' },
  'Comoros':                           { name: 'Comorian Franc',         symbol: 'Fr', code: 'KMF' },
  'Costa Rica':                        { name: 'Costa Rican Colón',      symbol: '₡',  code: 'CRC' },
  'Croatia':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Cuba':                              { name: 'Cuban Peso',             symbol: '$',  code: 'CUP' },
  'Cyprus':                            { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Czechia':                           { name: 'Czech Koruna',           symbol: 'Kč', code: 'CZK' },
  'Democratic Republic of Congo':      { name: 'Congolese Franc',        symbol: 'Fr', code: 'CDF' },
  'Denmark':                           { name: 'Danish Krone',           symbol: 'kr', code: 'DKK' },
  'Djibouti':                          { name: 'Djiboutian Franc',       symbol: 'Fr', code: 'DJF' },
  'Dominica':                          { name: 'East Caribbean Dollar',  symbol: '$',  code: 'XCD' },
  'Dominican Republic':                { name: 'Dominican Peso',         symbol: '$',  code: 'DOP' },
  'Ecuador':                           { name: 'United States Dollar',   symbol: '$',  code: 'USD' },
  'Egypt':                             { name: 'Egyptian Pound',         symbol: '£',  code: 'EGP' },
  'El Salvador':                       { name: 'United States Dollar',   symbol: '$',  code: 'USD' },
  'Equatorial Guinea':                 { name: 'Central African CFA Franc', symbol: 'Fr', code: 'XAF' },
  'Eritrea':                           { name: 'Eritrean Nakfa',         symbol: 'Nfk', code: 'ERN' },
  'Estonia':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Eswatini':                          { name: 'Swazi Lilangeni',        symbol: 'L',  code: 'SZL' },
  'Ethiopia':                          { name: 'Ethiopian Birr',         symbol: 'Br', code: 'ETB' },
  'Federated States of Micronesia':    { name: 'United States Dollar',   symbol: '$',  code: 'USD' },
  'Fiji':                              { name: 'Fijian Dollar',          symbol: '$',  code: 'FJD' },
  'Finland':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'France':                            { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Gabon':                             { name: 'Central African CFA Franc', symbol: 'Fr', code: 'XAF' },
  'Gambia':                            { name: 'Gambian Dalasi',         symbol: 'D',  code: 'GMD' },
  'Georgia':                           { name: 'Georgian Lari',          symbol: '₾',  code: 'GEL' },
  'Germany':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Ghana':                             { name: 'Ghanaian Cedi',          symbol: '₵',  code: 'GHS' },
  'Greece':                            { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Grenada':                           { name: 'East Caribbean Dollar',  symbol: '$',  code: 'XCD' },
  'Guatemala':                         { name: 'Guatemalan Quetzal',     symbol: 'Q',  code: 'GTQ' },
  'Guinea':                            { name: 'Guinean Franc',          symbol: 'Fr', code: 'GNF' },
  'Guinea-Bissau':                     { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Guyana':                            { name: 'Guyanese Dollar',        symbol: '$',  code: 'GYD' },
  'Haiti':                             { name: 'Haitian Gourde',         symbol: 'G',  code: 'HTG' },
  'Honduras':                          { name: 'Honduran Lempira',       symbol: 'L',  code: 'HNL' },
  'Hungary':                           { name: 'Hungarian Forint',       symbol: 'Ft', code: 'HUF' },
  'Iceland':                           { name: 'Icelandic Króna',        symbol: 'kr', code: 'ISK' },
  'India':                             { name: 'Indian Rupee',           symbol: '₹',  code: 'INR' },
  'Indonesia':                         { name: 'Indonesian Rupiah',      symbol: 'Rp', code: 'IDR' },
  'Iran':                              { name: 'Iranian Rial',           symbol: '﷼',  code: 'IRR' },
  'Iraq':                              { name: 'Iraqi Dinar',            symbol: 'ع.د', code: 'IQD' },
  'Ireland':                           { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Israel':                            { name: 'Israeli New Shekel',     symbol: '₪',  code: 'ILS' },
  'Italy':                             { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Ivory Coast':                       { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Jamaica':                           { name: 'Jamaican Dollar',        symbol: '$',  code: 'JMD' },
  'Japan':                             { name: 'Japanese Yen',           symbol: '¥',  code: 'JPY' },
  'Jordan':                            { name: 'Jordanian Dinar',        symbol: 'د.ا', code: 'JOD' },
  'Kazakhstan':                        { name: 'Kazakhstani Tenge',      symbol: '₸',  code: 'KZT' },
  'Kenya':                             { name: 'Kenyan Shilling',        symbol: 'KSh', code: 'KES' },
  'Kiribati':                          { name: 'Australian Dollar',      symbol: '$',  code: 'AUD' },
  'Kosovo':                            { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Kuwait':                            { name: 'Kuwaiti Dinar',          symbol: 'د.ك', code: 'KWD' },
  'Kyrgyzstan':                        { name: 'Kyrgystani Som',         symbol: 'лв', code: 'KGS' },
  'Laos':                              { name: 'Lao Kip',                symbol: '₭',  code: 'LAK' },
  'Latvia':                            { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Lebanon':                           { name: 'Lebanese Pound',         symbol: 'ل.ل', code: 'LBP' },
  'Lesotho':                           { name: 'Lesotho Loti',           symbol: 'L',  code: 'LSL' },
  'Liberia':                           { name: 'Liberian Dollar',        symbol: '$',  code: 'LRD' },
  'Libya':                             { name: 'Libyan Dinar',           symbol: 'ل.د', code: 'LYD' },
  'Liechtenstein':                     { name: 'Swiss Franc',            symbol: 'Fr', code: 'CHF' },
  'Lithuania':                         { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Luxembourg':                        { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Madagascar':                        { name: 'Malagasy Ariary',        symbol: 'Ar', code: 'MGA' },
  'Malawi':                            { name: 'Malawian Kwacha',        symbol: 'MK', code: 'MWK' },
  'Malaysia':                          { name: 'Malaysian Ringgit',      symbol: 'RM', code: 'MYR' },
  'Maldives':                          { name: 'Maldivian Rufiyaa',      symbol: 'Rf', code: 'MVR' },
  'Mali':                              { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Malta':                             { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Marshall Islands':                  { name: 'United States Dollar',   symbol: '$',  code: 'USD' },
  'Mauritania':                        { name: 'Mauritanian Ouguiya',    symbol: 'UM', code: 'MRU' },
  'Mauritius':                         { name: 'Mauritian Rupee',        symbol: '₨',  code: 'MUR' },
  'Mexico':                            { name: 'Mexican Peso',           symbol: '$',  code: 'MXN' },
  'Moldova':                           { name: 'Moldovan Leu',           symbol: 'L',  code: 'MDL' },
  'Monaco':                            { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Mongolia':                          { name: 'Mongolian Tögrög',       symbol: '₮',  code: 'MNT' },
  'Montenegro':                        { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Morocco':                           { name: 'Moroccan Dirham',        symbol: 'د.م.', code: 'MAD' },
  'Mozambique':                        { name: 'Mozambican Metical',     symbol: 'MT', code: 'MZN' },
  'Myanmar':                           { name: 'Myanmar Kyat',           symbol: 'K',  code: 'MMK' },
  'Namibia':                           { name: 'Namibian Dollar',        symbol: '$',  code: 'NAD' },
  'Nauru':                             { name: 'Australian Dollar',      symbol: '$',  code: 'AUD' },
  'Nepal':                             { name: 'Nepalese Rupee',         symbol: '₨',  code: 'NPR' },
  'Netherlands':                       { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'New Zealand':                       { name: 'New Zealand Dollar',     symbol: '$',  code: 'NZD' },
  'Nicaragua':                         { name: 'Nicaraguan Córdoba',     symbol: 'C$', code: 'NIO' },
  'Niger':                             { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Nigeria':                           { name: 'Nigerian Naira',         symbol: '₦',  code: 'NGN' },
  'North Korea':                       { name: 'North Korean Won',       symbol: '₩',  code: 'KPW' },
  'North Macedonia':                   { name: 'Macedonian Denar',       symbol: 'ден', code: 'MKD' },
  'Norway':                            { name: 'Norwegian Krone',        symbol: 'kr', code: 'NOK' },
  'Oman':                              { name: 'Omani Rial',             symbol: 'ر.ع.', code: 'OMR' },
  'Pakistan':                          { name: 'Pakistani Rupee',        symbol: '₨',  code: 'PKR' },
  'Palau':                             { name: 'United States Dollar',   symbol: '$',  code: 'USD' },
  'Panama':                            { name: 'Panamanian Balboa',      symbol: 'B/', code: 'PAB' },
  'Papua New Guinea':                  { name: 'Papua New Guinean Kina', symbol: 'K',  code: 'PGK' },
  'Paraguay':                          { name: 'Paraguayan Guaraní',     symbol: '₲',  code: 'PYG' },
  'Peru':                              { name: 'Peruvian Sol',           symbol: 'S/', code: 'PEN' },
  'Philippines':                       { name: 'Philippine Peso',        symbol: '₱',  code: 'PHP' },
  'Poland':                            { name: 'Polish Złoty',           symbol: 'zł', code: 'PLN' },
  'Portugal':                          { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Qatar':                             { name: 'Qatari Riyal',           symbol: 'ر.ق', code: 'QAR' },
  'Republic of the Congo':             { name: 'Central African CFA Franc', symbol: 'Fr', code: 'XAF' },
  'Romania':                           { name: 'Romanian Leu',           symbol: 'lei', code: 'RON' },
  'Russia':                            { name: 'Russian Ruble',          symbol: '₽',  code: 'RUB' },
  'Rwanda':                            { name: 'Rwandan Franc',          symbol: 'Fr', code: 'RWF' },
  'Saint Kitts and Nevis':             { name: 'East Caribbean Dollar',  symbol: '$',  code: 'XCD' },
  'Saint Lucia':                       { name: 'East Caribbean Dollar',  symbol: '$',  code: 'XCD' },
  'Saint Vincent and the Grenadines':  { name: 'East Caribbean Dollar',  symbol: '$',  code: 'XCD' },
  'Samoa':                             { name: 'Samoan Tālā',            symbol: 'T',  code: 'WST' },
  'San Marino':                        { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Saudi Arabia':                      { name: 'Saudi Riyal',            symbol: 'ر.س', code: 'SAR' },
  'Senegal':                           { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Serbia':                            { name: 'Serbian Dinar',          symbol: 'din', code: 'RSD' },
  'Seychelles':                        { name: 'Seychellois Rupee',      symbol: '₨',  code: 'SCR' },
  'Sierra Leone':                      { name: 'Sierra Leonean Leone',   symbol: 'Le', code: 'SLL' },
  'Singapore':                         { name: 'Singapore Dollar',       symbol: '$',  code: 'SGD' },
  'Slovakia':                          { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Slovenia':                          { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Solomon Islands':                   { name: 'Solomon Islands Dollar', symbol: '$',  code: 'SBD' },
  'Somalia':                           { name: 'Somali Shilling',        symbol: 'Sh', code: 'SOS' },
  'South Africa':                      { name: 'South African Rand',     symbol: 'R',  code: 'ZAR' },
  'South Korea':                       { name: 'South Korean Won',       symbol: '₩',  code: 'KRW' },
  'South Sudan':                       { name: 'South Sudanese Pound',   symbol: '£',  code: 'SSP' },
  'Spain':                             { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Sri Lanka':                         { name: 'Sri Lankan Rupee',       symbol: '₨',  code: 'LKR' },
  'Sudan':                             { name: 'Sudanese Pound',         symbol: '£',  code: 'SDG' },
  'Suriname':                          { name: 'Surinamese Dollar',      symbol: '$',  code: 'SRD' },
  'Sweden':                            { name: 'Swedish Krona',          symbol: 'kr', code: 'SEK' },
  'Switzerland':                       { name: 'Swiss Franc',            symbol: 'Fr', code: 'CHF' },
  'Syria':                             { name: 'Syrian Pound',           symbol: '£',  code: 'SYP' },
  'São Tomé and Príncipe':             { name: 'São Tomé and Príncipe Dobra', symbol: 'Db', code: 'STN' },
  'Taiwan':                            { name: 'New Taiwan Dollar',      symbol: '$',  code: 'TWD' },
  'Tajikistan':                        { name: 'Tajikistani Somoni',     symbol: 'SM', code: 'TJS' },
  'Tanzania':                          { name: 'Tanzanian Shilling',     symbol: 'Sh', code: 'TZS' },
  'Thailand':                          { name: 'Thai Baht',              symbol: '฿',  code: 'THB' },
  'Timor-Leste':                       { name: 'United States Dollar',   symbol: '$',  code: 'USD' },
  'Togo':                              { name: 'West African CFA Franc', symbol: 'Fr', code: 'XOF' },
  'Tonga':                             { name: 'Tongan Paʻanga',         symbol: 'T$', code: 'TOP' },
  'Trinidad and Tobago':               { name: 'Trinidad and Tobago Dollar', symbol: '$', code: 'TTD' },
  'Tunisia':                           { name: 'Tunisian Dinar',         symbol: 'د.ت', code: 'TND' },
  'Turkey':                            { name: 'Turkish Lira',           symbol: '₺',  code: 'TRY' },
  'Turkmenistan':                      { name: 'Turkmenistani Manat',    symbol: 'T',  code: 'TMT' },
  'Tuvalu':                            { name: 'Australian Dollar',      symbol: '$',  code: 'AUD' },
  'Uganda':                            { name: 'Ugandan Shilling',       symbol: 'Sh', code: 'UGX' },
  'Ukraine':                           { name: 'Ukrainian Hryvnia',      symbol: '₴',  code: 'UAH' },
  'United Arab Emirates':              { name: 'UAE Dirham',             symbol: 'د.إ', code: 'AED' },
  'United Kingdom':                    { name: 'British Pound Sterling',  symbol: '£',  code: 'GBP' },
  'United States of America':          { name: 'United States Dollar',   symbol: '$',  code: 'USD' },
  'Uruguay':                           { name: 'Uruguayan Peso',         symbol: '$',  code: 'UYU' },
  'Uzbekistan':                        { name: 'Uzbekistani Som',        symbol: 'лв', code: 'UZS' },
  'Vanuatu':                           { name: 'Vanuatu Vatu',           symbol: 'Vt', code: 'VUV' },
  'Vatican City':                      { name: 'Euro',                   symbol: '€',  code: 'EUR' },
  'Venezuela':                         { name: 'Venezuelan Bolívar',     symbol: 'Bs.', code: 'VES' },
  'Vietnam':                           { name: 'Vietnamese Đồng',        symbol: '₫',  code: 'VND' },
  'Yemen':                             { name: 'Yemeni Rial',            symbol: '﷼',  code: 'YER' },
  'Zambia':                            { name: 'Zambian Kwacha',         symbol: 'ZK', code: 'ZMW' },
  'Zimbabwe':                          { name: 'Zimbabwean Dollar',      symbol: '$',  code: 'ZWL' },
}

// Unique currency names for random distractors in the game
export const ALL_CURRENCY_NAMES = [
  ...new Set(Object.values(COUNTRY_CURRENCY).map(c => c.name))
].sort()
