// flag emoji + continent keyed by app NAME (after NAME_OVERRIDES)
export const COUNTRY_INFO = {
  // ── Africa ────────────────────────────────────────────────────────────────
  'Algeria':                      { flag: '🇩🇿', continent: 'Africa' },
  'Angola':                       { flag: '🇦🇴', continent: 'Africa' },
  'Benin':                        { flag: '🇧🇯', continent: 'Africa' },
  'Botswana':                     { flag: '🇧🇼', continent: 'Africa' },
  'Burkina Faso':                 { flag: '🇧🇫', continent: 'Africa' },
  'Burundi':                      { flag: '🇧🇮', continent: 'Africa' },
  'Cabo Verde':                   { flag: '🇨🇻', continent: 'Africa' },
  'Cameroon':                     { flag: '🇨🇲', continent: 'Africa' },
  'CAR':                          { flag: '🇨🇫', continent: 'Africa' },
  'Chad':                         { flag: '🇹🇩', continent: 'Africa' },
  'Comoros':                      { flag: '🇰🇲', continent: 'Africa' },
  'Congo':                        { flag: '🇨🇬', continent: 'Africa' },
  'Dem. Rep. Congo':              { flag: '🇨🇩', continent: 'Africa' },
  'Djibouti':                     { flag: '🇩🇯', continent: 'Africa' },
  'Egypt':                        { flag: '🇪🇬', continent: 'Africa' },
  'Eq. Guinea':                   { flag: '🇬🇶', continent: 'Africa' },
  'Eritrea':                      { flag: '🇪🇷', continent: 'Africa' },
  'Eswatini':                     { flag: '🇸🇿', continent: 'Africa' },
  'Ethiopia':                     { flag: '🇪🇹', continent: 'Africa' },
  'Gabon':                        { flag: '🇬🇦', continent: 'Africa' },
  'Gambia':                       { flag: '🇬🇲', continent: 'Africa' },
  'Ghana':                        { flag: '🇬🇭', continent: 'Africa' },
  'Guinea':                       { flag: '🇬🇳', continent: 'Africa' },
  'Guinea-Bissau':                { flag: '🇬🇼', continent: 'Africa' },
  'Ivory Coast':                  { flag: '🇨🇮', continent: 'Africa' },
  'Kenya':                        { flag: '🇰🇪', continent: 'Africa' },
  'Lesotho':                      { flag: '🇱🇸', continent: 'Africa' },
  'Liberia':                      { flag: '🇱🇷', continent: 'Africa' },
  'Libya':                        { flag: '🇱🇾', continent: 'Africa' },
  'Madagascar':                   { flag: '🇲🇬', continent: 'Africa' },
  'Malawi':                       { flag: '🇲🇼', continent: 'Africa' },
  'Mali':                         { flag: '🇲🇱', continent: 'Africa' },
  'Mauritania':                   { flag: '🇲🇷', continent: 'Africa' },
  'Mauritius':                    { flag: '🇲🇺', continent: 'Africa' },
  'Morocco':                      { flag: '🇲🇦', continent: 'Africa' },
  'Mozambique':                   { flag: '🇲🇿', continent: 'Africa' },
  'Namibia':                      { flag: '🇳🇦', continent: 'Africa' },
  'Niger':                        { flag: '🇳🇪', continent: 'Africa' },
  'Nigeria':                      { flag: '🇳🇬', continent: 'Africa' },
  'Rwanda':                       { flag: '🇷🇼', continent: 'Africa' },
  'Sao Tome and Principe':        { flag: '🇸🇹', continent: 'Africa' },
  'Senegal':                      { flag: '🇸🇳', continent: 'Africa' },
  'Seychelles':                   { flag: '🇸🇨', continent: 'Africa' },
  'Sierra Leone':                 { flag: '🇸🇱', continent: 'Africa' },
  'Somalia':                      { flag: '🇸🇴', continent: 'Africa' },
  'South Africa':                 { flag: '🇿🇦', continent: 'Africa' },
  'South Sudan':                  { flag: '🇸🇸', continent: 'Africa' },
  'Sudan':                        { flag: '🇸🇩', continent: 'Africa' },
  'Tanzania':                     { flag: '🇹🇿', continent: 'Africa' },
  'Togo':                         { flag: '🇹🇬', continent: 'Africa' },
  'Tunisia':                      { flag: '🇹🇳', continent: 'Africa' },
  'Uganda':                       { flag: '🇺🇬', continent: 'Africa' },
  'Zambia':                       { flag: '🇿🇲', continent: 'Africa' },
  'Zimbabwe':                     { flag: '🇿🇼', continent: 'Africa' },

  // ── Americas ──────────────────────────────────────────────────────────────
  'Antigua and Barbuda':          { flag: '🇦🇬', continent: 'Americas' },
  'Argentina':                    { flag: '🇦🇷', continent: 'Americas' },
  'Bahamas':                      { flag: '🇧🇸', continent: 'Americas' },
  'Barbados':                     { flag: '🇧🇧', continent: 'Americas' },
  'Belize':                       { flag: '🇧🇿', continent: 'Americas' },
  'Bolivia':                      { flag: '🇧🇴', continent: 'Americas' },
  'Brazil':                       { flag: '🇧🇷', continent: 'Americas' },
  'Canada':                       { flag: '🇨🇦', continent: 'Americas' },
  'Chile':                        { flag: '🇨🇱', continent: 'Americas' },
  'Colombia':                     { flag: '🇨🇴', continent: 'Americas' },
  'Costa Rica':                   { flag: '🇨🇷', continent: 'Americas' },
  'Cuba':                         { flag: '🇨🇺', continent: 'Americas' },
  'Dominica':                     { flag: '🇩🇲', continent: 'Americas' },
  'Dominican Rep.':               { flag: '🇩🇴', continent: 'Americas' },
  'Ecuador':                      { flag: '🇪🇨', continent: 'Americas' },
  'El Salvador':                  { flag: '🇸🇻', continent: 'Americas' },
  'Grenada':                      { flag: '🇬🇩', continent: 'Americas' },
  'Guatemala':                    { flag: '🇬🇹', continent: 'Americas' },
  'Guyana':                       { flag: '🇬🇾', continent: 'Americas' },
  'Haiti':                        { flag: '🇭🇹', continent: 'Americas' },
  'Honduras':                     { flag: '🇭🇳', continent: 'Americas' },
  'Jamaica':                      { flag: '🇯🇲', continent: 'Americas' },
  'Mexico':                       { flag: '🇲🇽', continent: 'Americas' },
  'Nicaragua':                    { flag: '🇳🇮', continent: 'Americas' },
  'Panama':                       { flag: '🇵🇦', continent: 'Americas' },
  'Paraguay':                     { flag: '🇵🇾', continent: 'Americas' },
  'Peru':                         { flag: '🇵🇪', continent: 'Americas' },
  'Saint Kitts and Nevis':        { flag: '🇰🇳', continent: 'Americas' },
  'Saint Lucia':                  { flag: '🇱🇨', continent: 'Americas' },
  'Saint Vincent and the Grenadines': { flag: '🇻🇨', continent: 'Americas' },
  'Suriname':                     { flag: '🇸🇷', continent: 'Americas' },
  'Trinidad and Tobago':          { flag: '🇹🇹', continent: 'Americas' },
  'USA':                          { flag: '🇺🇸', continent: 'Americas' },
  'Uruguay':                      { flag: '🇺🇾', continent: 'Americas' },
  'Venezuela':                    { flag: '🇻🇪', continent: 'Americas' },

  // ── Asia ──────────────────────────────────────────────────────────────────
  'Afghanistan':                  { flag: '🇦🇫', continent: 'Asia' },
  'Armenia':                      { flag: '🇦🇲', continent: 'Asia' },
  'Azerbaijan':                   { flag: '🇦🇿', continent: 'Asia' },
  'Bahrain':                      { flag: '🇧🇭', continent: 'Asia' },
  'Bangladesh':                   { flag: '🇧🇩', continent: 'Asia' },
  'Bhutan':                       { flag: '🇧🇹', continent: 'Asia' },
  'Brunei':                       { flag: '🇧🇳', continent: 'Asia' },
  'Cambodia':                     { flag: '🇰🇭', continent: 'Asia' },
  'China':                        { flag: '🇨🇳', continent: 'Asia' },
  'Cyprus':                       { flag: '🇨🇾', continent: 'Asia' },
  'Georgia':                      { flag: '🇬🇪', continent: 'Asia' },
  'India':                        { flag: '🇮🇳', continent: 'Asia' },
  'Indonesia':                    { flag: '🇮🇩', continent: 'Asia' },
  'Iran':                         { flag: '🇮🇷', continent: 'Asia' },
  'Iraq':                         { flag: '🇮🇶', continent: 'Asia' },
  'Israel':                       { flag: '🇮🇱', continent: 'Asia' },
  'Japan':                        { flag: '🇯🇵', continent: 'Asia' },
  'Jordan':                       { flag: '🇯🇴', continent: 'Asia' },
  'Kazakhstan':                   { flag: '🇰🇿', continent: 'Asia' },
  'Kuwait':                       { flag: '🇰🇼', continent: 'Asia' },
  'Kyrgyzstan':                   { flag: '🇰🇬', continent: 'Asia' },
  'Laos':                         { flag: '🇱🇦', continent: 'Asia' },
  'Lebanon':                      { flag: '🇱🇧', continent: 'Asia' },
  'Malaysia':                     { flag: '🇲🇾', continent: 'Asia' },
  'Maldives':                     { flag: '🇲🇻', continent: 'Asia' },
  'Mongolia':                     { flag: '🇲🇳', continent: 'Asia' },
  'Myanmar':                      { flag: '🇲🇲', continent: 'Asia' },
  'Nepal':                        { flag: '🇳🇵', continent: 'Asia' },
  'North Korea':                  { flag: '🇰🇵', continent: 'Asia' },
  'Oman':                         { flag: '🇴🇲', continent: 'Asia' },
  'Pakistan':                     { flag: '🇵🇰', continent: 'Asia' },
  'Palestine':                    { flag: '🇵🇸', continent: 'Asia' },
  'Philippines':                  { flag: '🇵🇭', continent: 'Asia' },
  'Qatar':                        { flag: '🇶🇦', continent: 'Asia' },
  'Saudi Arabia':                 { flag: '🇸🇦', continent: 'Asia' },
  'Singapore':                    { flag: '🇸🇬', continent: 'Asia' },
  'South Korea':                  { flag: '🇰🇷', continent: 'Asia' },
  'Sri Lanka':                    { flag: '🇱🇰', continent: 'Asia' },
  'Syria':                        { flag: '🇸🇾', continent: 'Asia' },
  'Taiwan':                       { flag: '🇹🇼', continent: 'Asia' },
  'Tajikistan':                   { flag: '🇹🇯', continent: 'Asia' },
  'Thailand':                     { flag: '🇹🇭', continent: 'Asia' },
  'Timor-Leste':                  { flag: '🇹🇱', continent: 'Asia' },
  'Turkey':                       { flag: '🇹🇷', continent: 'Asia' },
  'Turkmenistan':                 { flag: '🇹🇲', continent: 'Asia' },
  'UAE':                          { flag: '🇦🇪', continent: 'Asia' },
  'Uzbekistan':                   { flag: '🇺🇿', continent: 'Asia' },
  'Vietnam':                      { flag: '🇻🇳', continent: 'Asia' },
  'Yemen':                        { flag: '🇾🇪', continent: 'Asia' },

  // ── Europe ────────────────────────────────────────────────────────────────
  'Albania':                      { flag: '🇦🇱', continent: 'Europe' },
  'Andorra':                      { flag: '🇦🇩', continent: 'Europe' },
  'Austria':                      { flag: '🇦🇹', continent: 'Europe' },
  'Belarus':                      { flag: '🇧🇾', continent: 'Europe' },
  'Belgium':                      { flag: '🇧🇪', continent: 'Europe' },
  'Bosnia and Herzegovina':       { flag: '🇧🇦', continent: 'Europe' },
  'Bulgaria':                     { flag: '🇧🇬', continent: 'Europe' },
  'Croatia':                      { flag: '🇭🇷', continent: 'Europe' },
  'Czech Republic':               { flag: '🇨🇿', continent: 'Europe' },
  'Denmark':                      { flag: '🇩🇰', continent: 'Europe' },
  'Estonia':                      { flag: '🇪🇪', continent: 'Europe' },
  'Finland':                      { flag: '🇫🇮', continent: 'Europe' },
  'France':                       { flag: '🇫🇷', continent: 'Europe' },
  'Germany':                      { flag: '🇩🇪', continent: 'Europe' },
  'Greece':                       { flag: '🇬🇷', continent: 'Europe' },
  'Hungary':                      { flag: '🇭🇺', continent: 'Europe' },
  'Iceland':                      { flag: '🇮🇸', continent: 'Europe' },
  'Ireland':                      { flag: '🇮🇪', continent: 'Europe' },
  'Italy':                        { flag: '🇮🇹', continent: 'Europe' },
  'Kosovo':                       { flag: '🇽🇰', continent: 'Europe' },
  'Latvia':                       { flag: '🇱🇻', continent: 'Europe' },
  'Liechtenstein':                { flag: '🇱🇮', continent: 'Europe' },
  'Lithuania':                    { flag: '🇱🇹', continent: 'Europe' },
  'Luxembourg':                   { flag: '🇱🇺', continent: 'Europe' },
  'Malta':                        { flag: '🇲🇹', continent: 'Europe' },
  'Moldova':                      { flag: '🇲🇩', continent: 'Europe' },
  'Monaco':                       { flag: '🇲🇨', continent: 'Europe' },
  'Montenegro':                   { flag: '🇲🇪', continent: 'Europe' },
  'Netherlands':                  { flag: '🇳🇱', continent: 'Europe' },
  'North Macedonia':              { flag: '🇲🇰', continent: 'Europe' },
  'Norway':                       { flag: '🇳🇴', continent: 'Europe' },
  'Poland':                       { flag: '🇵🇱', continent: 'Europe' },
  'Portugal':                     { flag: '🇵🇹', continent: 'Europe' },
  'Romania':                      { flag: '🇷🇴', continent: 'Europe' },
  'Russia':                       { flag: '🇷🇺', continent: 'Europe' },
  'San Marino':                   { flag: '🇸🇲', continent: 'Europe' },
  'Serbia':                       { flag: '🇷🇸', continent: 'Europe' },
  'Slovakia':                     { flag: '🇸🇰', continent: 'Europe' },
  'Slovenia':                     { flag: '🇸🇮', continent: 'Europe' },
  'Spain':                        { flag: '🇪🇸', continent: 'Europe' },
  'Sweden':                       { flag: '🇸🇪', continent: 'Europe' },
  'Switzerland':                  { flag: '🇨🇭', continent: 'Europe' },
  'Ukraine':                      { flag: '🇺🇦', continent: 'Europe' },
  'UK':                           { flag: '🇬🇧', continent: 'Europe' },
  'Vatican':                      { flag: '🇻🇦', continent: 'Europe' },

  // ── Oceania ───────────────────────────────────────────────────────────────
  'Australia':                    { flag: '🇦🇺', continent: 'Oceania' },
  'Fiji':                         { flag: '🇫🇯', continent: 'Oceania' },
  'Kiribati':                     { flag: '🇰🇮', continent: 'Oceania' },
  'Marshall Islands':             { flag: '🇲🇭', continent: 'Oceania' },
  'Federated States of Micronesia': { flag: '🇫🇲', continent: 'Oceania' },
  'Nauru':                        { flag: '🇳🇷', continent: 'Oceania' },
  'New Zealand':                  { flag: '🇳🇿', continent: 'Oceania' },
  'Palau':                        { flag: '🇵🇼', continent: 'Oceania' },
  'Papua New Guinea':             { flag: '🇵🇬', continent: 'Oceania' },
  'Samoa':                        { flag: '🇼🇸', continent: 'Oceania' },
  'Solomon Islands':              { flag: '🇸🇧', continent: 'Oceania' },
  'Tonga':                        { flag: '🇹🇴', continent: 'Oceania' },
  'Tuvalu':                       { flag: '🇹🇻', continent: 'Oceania' },
  'Vanuatu':                      { flag: '🇻🇺', continent: 'Oceania' },
}
