/**
 * Emoji clues for Country Emoji quiz.
 * 3–4 emojis that hint at each country without being too obvious.
 */
export const EMOJI_CLUES = [
  { country: 'France',              emojis: ['🗼', '🥖', '🍷', '🧀'] },
  { country: 'Japan',               emojis: ['🗻', '🍣', '🌸', '⛩️'] },
  { country: 'Brazil',              emojis: ['🌴', '🎭', '⚽', '🌊'] },
  { country: 'Egypt',               emojis: ['🔺', '🐪', '🏜️', '🌊'] },
  { country: 'Australia',           emojis: ['🦘', '🪃', '🏄', '🐨'] },
  { country: 'India',               emojis: ['🐘', '🌶️', '🕌', '🎭'] },
  { country: 'Russia',              emojis: ['🐻', '❄️', '🏔️', '🎭'] },
  { country: 'China',               emojis: ['🐉', '🐼', '🍜', '🧱'] },
  { country: 'Italy',               emojis: ['🍕', '🛵', '🏛️', '🎭'] },
  { country: 'Spain',               emojis: ['🐂', '💃', '🌞', '🏖️'] },
  { country: 'Germany',             emojis: ['🍺', '🏰', '⚙️', '🌲'] },
  { country: 'United States',       emojis: ['🗽', '🦅', '🍔', '🎬'] },
  { country: 'United Kingdom',      emojis: ['☕', '👑', '🎩', '🚌'] },
  { country: 'Canada',              emojis: ['🍁', '🏒', '🫐', '❄️'] },
  { country: 'Mexico',              emojis: ['🌮', '🌵', '🎸', '💀'] },
  { country: 'Greece',              emojis: ['🏛️', '🫒', '🌊', '🏺'] },
  { country: 'Turkey',              emojis: ['🌙', '🌹', '☕', '🕌'] },
  { country: 'South Africa',        emojis: ['🦁', '🏉', '🌈', '💎'] },
  { country: 'Argentina',           emojis: ['💃', '🥩', '⚽', '🐄'] },
  { country: 'Netherlands',         emojis: ['🌷', '🚲', '🧀', '💨'] },
  { country: 'Switzerland',         emojis: ['⛷️', '🍫', '⌚', '🏔️'] },
  { country: 'Norway',              emojis: ['🌌', '🐟', '🎿', '⛵'] },
  { country: 'Sweden',              emojis: ['🛋️', '🍓', '🎤', '🌲'] },
  { country: 'Finland',             emojis: ['🎅', '🧊', '🦌', '🌲'] },
  { country: 'Denmark',             emojis: ['🧱', '🧜‍♀️', '🥐', '🚲'] },
  { country: 'Portugal',            emojis: ['🐟', '🌊', '🎸', '⛵'] },
  { country: 'Ireland',             emojis: ['🍀', '🍺', '🎻', '☘️'] },
  { country: 'Poland',              emojis: ['🥟', '🏰', '🎻', '🦅'] },
  { country: 'Ukraine',             emojis: ['🌻', '🌾', '🏺', '🔵'] },
  { country: 'Romania',             emojis: ['🧄', '🏰', '🐺', '🌲'] },
  { country: 'Hungary',             emojis: ['🌶️', '🍲', '🏊', '🏰'] },
  { country: 'Czech Republic',      emojis: ['🍺', '🏰', '🎭', '🎻'] },
  { country: 'Thailand',            emojis: ['🐘', '🙏', '🌶️', '🏯'] },
  { country: 'Vietnam',             emojis: ['🍜', '🛵', '🌾', '🎋'] },
  { country: 'Indonesia',           emojis: ['🏝️', '🌋', '🛕', '🦧'] },
  { country: 'Philippines',         emojis: ['🏝️', '🌺', '🐠', '🎉'] },
  { country: 'Pakistan',            emojis: ['🏔️', '🌙', '🍛', '🎪'] },
  { country: 'Saudi Arabia',        emojis: ['🐪', '🏜️', '⛽', '🕌'] },
  { country: 'Iran',                emojis: ['🏺', '🌹', '🎭', '⛰️'] },
  { country: 'Morocco',             emojis: ['🕌', '🌴', '🍵', '🪬'] },
  { country: 'Nigeria',             emojis: ['🥁', '🎵', '🌴', '🦅'] },
  { country: 'Ghana',               emojis: ['🥁', '🌟', '🎭', '🌴'] },
  { country: 'Kenya',               emojis: ['🦒', '🏃', '☕', '🌍'] },
  { country: 'Ethiopia',            emojis: ['☕', '🏃', '🦁', '🌿'] },
  { country: 'Tanzania',            emojis: ['🦒', '🌋', '🦁', '🏔️'] },
  { country: 'Colombia',            emojis: ['☕', '🌸', '💛', '🌺'] },
  { country: 'Peru',                emojis: ['🦙', '🏔️', '🌽', '🍋'] },
  { country: 'Chile',               emojis: ['🌶️', '🍷', '🏔️', '🐧'] },
  { country: 'Cuba',                emojis: ['🎺', '🍹', '🚗', '🎭'] },
  { country: 'Jamaica',             emojis: ['🏃', '🌴', '🎵', '☀️'] },
  { country: 'New Zealand',         emojis: ['🐑', '🏉', '🌿', '🗻'] },
  { country: 'Mongolia',            emojis: ['🐎', '🏕️', '🦅', '🌾'] },
  { country: 'Nepal',               emojis: ['🏔️', '🧘', '🥾', '🙏'] },
  { country: 'Sri Lanka',           emojis: ['🦁', '🍵', '🏖️', '🐘'] },
  { country: 'Cambodia',            emojis: ['🏛️', '🌺', '🎭', '🌿'] },
  { country: 'Myanmar',             emojis: ['🛕', '🌿', '🍚', '🐘'] },
  { country: 'Madagascar',          emojis: ['🦎', '🐒', '🌺', '🏝️'] },
  { country: 'Iceland',             emojis: ['🌋', '🌌', '🎣', '♨️'] },
  { country: 'Israel',              emojis: ['🕎', '🏜️', '🍊', '✡️'] },
  { country: 'Jordan',              emojis: ['🏜️', '🐪', '🏛️', '🌹'] },
  { country: 'Lebanon',             emojis: ['🌲', '🍋', '🕌', '🎭'] },
  { country: 'Iraq',                emojis: ['🏺', '🛢️', '🌴', '🐪'] },
  { country: 'Kazakhstan',          emojis: ['🦅', '🐎', '🌾', '⛽'] },
  { country: 'Uzbekistan',          emojis: ['🕌', '🍑', '🏺', '🌾'] },
  { country: 'Georgia',             emojis: ['🍷', '🏔️', '🏰', '⛪'] },
  { country: 'Armenia',             emojis: ['🏔️', '🍷', '⛪', '🎻'] },
  { country: 'Azerbaijan',          emojis: ['🔥', '🛢️', '🏔️', '🌙'] },
  { country: 'Serbia',              emojis: ['🥩', '🏀', '🎻', '🏰'] },
  { country: 'Croatia',             emojis: ['🏖️', '⛵', '🏰', '⚽'] },
  { country: 'Bulgaria',            emojis: ['🌹', '🌲', '🎻', '🏔️'] },
  { country: 'Austria',             emojis: ['🎼', '⛷️', '☕', '🏰'] },
  { country: 'Belgium',             emojis: ['🍫', '🍟', '🍺', '🌷'] },
  { country: 'Scotland',            emojis: ['🏴󠁧󠁢󠁳󠁣󠁴󠁿', '🥃', '🎸', '🌿'] },
  { country: 'Singapore',           emojis: ['🦁', '🌆', '🍜', '✈️'] },
  { country: 'Bhutan',              emojis: ['🐉', '🏔️', '⚡', '🧘'] },
  { country: 'Bolivia',             emojis: ['🦙', '🏔️', '🌈', '🧢'] },
  { country: 'Venezuela',           emojis: ['🛢️', '🌴', '🎭', '🦜'] },
  { country: 'Ecuador',             emojis: ['🦎', '🌋', '🐢', '🌺'] },
  { country: 'Panama',              emojis: ['⛵', '🌉', '🎩', '🐊'] },
  { country: 'Costa Rica',          emojis: ['🐸', '🌿', '☕', '🦜'] },
  { country: 'Cuba',                emojis: ['🎺', '🍹', '🚗', '🎭'] },
  { country: 'Uruguay',             emojis: ['🥩', '🌊', '⚽', '🌅'] },
  { country: 'Paraguay',            emojis: ['🌿', '🎭', '🌊', '🍵'] },
  { country: 'Zambia',              emojis: ['🌊', '🦁', '☀️', '🌿'] },
  { country: 'Zimbabwe',            emojis: ['🏛️', '🦅', '🌿', '💎'] },
  { country: 'Uganda',              emojis: ['🦍', '🐦', '🏔️', '☕'] },
  { country: 'Rwanda',              emojis: ['🦍', '🌿', '🌄', '☕'] },
  { country: 'Senegal',             emojis: ['🥁', '🦁', '🌊', '🎭'] },
  { country: 'Tunisia',             emojis: ['🕌', '🏖️', '🌹', '🫒'] },
  { country: 'Algeria',             emojis: ['🕌', '🏜️', '🌹', '🫒'] },
  { country: 'Libya',               emojis: ['🏜️', '🛢️', '🌴', '🕌'] },
  { country: 'Sudan',               emojis: ['🏜️', '🌊', '🐪', '⛩️'] },
  { country: 'Mozambique',          emojis: ['🌊', '🎸', '🌴', '🦁'] },
  { country: 'Angola',              emojis: ['💎', '🛢️', '🌴', '🎭'] },
  { country: 'Cameroon',            emojis: ['🦍', '☕', '🌿', '🌊'] },
  { country: 'Malaysia',            emojis: ['🏝️', '🌴', '🍢', '🛕'] },
  { country: 'South Korea',         emojis: ['🤖', '🎮', '🍜', '🎤'] },
  { country: 'North Korea',         emojis: ['🚀', '🎭', '🌽', '🏔️'] },
  { country: 'Taiwan',              emojis: ['🫧', '🧋', '🏔️', '🎍'] },
  { country: 'Bangladesh',          emojis: ['🌿', '🌊', '🧵', '🦐'] },
  { country: 'Maldives',            emojis: ['🏝️', '🤿', '🌊', '🐠'] },
  { country: 'Papua New Guinea',    emojis: ['🦜', '🌿', '🥁', '🏝️'] },
  { country: 'Fiji',                emojis: ['🏝️', '🏉', '🌴', '🌊'] },
]
