/**
 * Approximate dominant flag colors per country.
 * Percentages are visual estimates, not pixel-accurate.
 * hex: CSS color, name: display label, pct: approximate % of flag area.
 */
export const FLAG_COLORS = {
  'Afghanistan':              [{ hex: '#000000', name: 'Black',  pct: 33 }, { hex: '#BF0000', name: 'Red',    pct: 33 }, { hex: '#009000', name: 'Green',  pct: 34 }],
  'Albania':                  [{ hex: '#E41E20', name: 'Red',    pct: 67 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'Algeria':                  [{ hex: '#006233', name: 'Green',  pct: 50 }, { hex: '#FFFFFF', name: 'White',  pct: 45 }, { hex: '#D21034', name: 'Red',    pct: 5  }],
  'Angola':                   [{ hex: '#CC0000', name: 'Red',    pct: 50 }, { hex: '#000000', name: 'Black',  pct: 50 }],
  'Argentina':                [{ hex: '#74ACDF', name: 'Sky Blue', pct: 50 }, { hex: '#FFFFFF', name: 'White', pct: 50 }],
  'Armenia':                  [{ hex: '#D90012', name: 'Red',    pct: 33 }, { hex: '#0033A0', name: 'Blue',   pct: 33 }, { hex: '#F2A800', name: 'Orange', pct: 34 }],
  'Australia':                [{ hex: '#003087', name: 'Blue',   pct: 55 }, { hex: '#CC142B', name: 'Red',    pct: 25 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }],
  'Austria':                  [{ hex: '#ED2939', name: 'Red',    pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Azerbaijan':               [{ hex: '#0092BC', name: 'Blue',   pct: 33 }, { hex: '#E8192C', name: 'Red',    pct: 33 }, { hex: '#00AF66', name: 'Green',  pct: 34 }],
  'Bahamas':                  [{ hex: '#00778B', name: 'Aqua',   pct: 67 }, { hex: '#FFC72C', name: 'Yellow', pct: 20 }, { hex: '#000000', name: 'Black',  pct: 13 }],
  'Bahrain':                  [{ hex: '#CE1126', name: 'Red',    pct: 75 }, { hex: '#FFFFFF', name: 'White',  pct: 25 }],
  'Bangladesh':               [{ hex: '#006A4E', name: 'Green',  pct: 80 }, { hex: '#F42A41', name: 'Red',    pct: 20 }],
  'Belarus':                  [{ hex: '#CF101A', name: 'Red',    pct: 67 }, { hex: '#009A44', name: 'Green',  pct: 28 }, { hex: '#FFFFFF', name: 'White',  pct: 5  }],
  'Belgium':                  [{ hex: '#000000', name: 'Black',  pct: 33 }, { hex: '#FAE042', name: 'Yellow', pct: 34 }, { hex: '#EF3340', name: 'Red',    pct: 33 }],
  'Belize':                   [{ hex: '#003F87', name: 'Blue',   pct: 75 }, { hex: '#CE1126', name: 'Red',    pct: 15 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }],
  'Benin':                    [{ hex: '#008751', name: 'Green',  pct: 33 }, { hex: '#FCD116', name: 'Yellow', pct: 34 }, { hex: '#E8112D', name: 'Red',    pct: 33 }],
  'Bhutan':                   [{ hex: '#FF8000', name: 'Orange', pct: 50 }, { hex: '#E5E5E5', name: 'White',  pct: 50 }],
  'Bolivia':                  [{ hex: '#D52B1E', name: 'Red',    pct: 33 }, { hex: '#F4E400', name: 'Yellow', pct: 34 }, { hex: '#007A3D', name: 'Green',  pct: 33 }],
  'Bosnia and Herzegovina':   [{ hex: '#002395', name: 'Blue',   pct: 70 }, { hex: '#FFCD00', name: 'Yellow', pct: 20 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }],
  'Botswana':                 [{ hex: '#75AADB', name: 'Blue',   pct: 60 }, { hex: '#000000', name: 'Black',  pct: 25 }, { hex: '#FFFFFF', name: 'White',  pct: 15 }],
  'Brazil':                   [{ hex: '#009C3B', name: 'Green',  pct: 60 }, { hex: '#FFDF00', name: 'Yellow', pct: 20 }, { hex: '#002776', name: 'Blue',   pct: 15 }, { hex: '#FFFFFF', name: 'White', pct: 5 }],
  'Brunei':                   [{ hex: '#F7E017', name: 'Yellow', pct: 60 }, { hex: '#FFFFFF', name: 'White',  pct: 25 }, { hex: '#000000', name: 'Black',  pct: 15 }],
  'Bulgaria':                 [{ hex: '#FFFFFF', name: 'White',  pct: 33 }, { hex: '#00966E', name: 'Green',  pct: 34 }, { hex: '#D62612', name: 'Red',    pct: 33 }],
  'Burkina Faso':             [{ hex: '#EF2B2D', name: 'Red',    pct: 50 }, { hex: '#009A00', name: 'Green',  pct: 45 }, { hex: '#FCD116', name: 'Yellow', pct: 5  }],
  'Burundi':                  [{ hex: '#CE1126', name: 'Red',    pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 30 }, { hex: '#18A050', name: 'Green',  pct: 30 }],
  'Cambodia':                 [{ hex: '#032EA1', name: 'Blue',   pct: 40 }, { hex: '#E00025', name: 'Red',    pct: 60 }],
  'Cameroon':                 [{ hex: '#007A5E', name: 'Green',  pct: 33 }, { hex: '#CE1126', name: 'Red',    pct: 34 }, { hex: '#FCD116', name: 'Yellow', pct: 33 }],
  'Canada':                   [{ hex: '#FF0000', name: 'Red',    pct: 50 }, { hex: '#FFFFFF', name: 'White',  pct: 50 }],
  'Central African Republic': [{ hex: '#003082', name: 'Blue',   pct: 20 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }, { hex: '#009A00', name: 'Green',  pct: 20 }, { hex: '#FFCB00', name: 'Yellow', pct: 20 }],
  'Chad':                     [{ hex: '#002664', name: 'Blue',   pct: 33 }, { hex: '#FECB00', name: 'Yellow', pct: 34 }, { hex: '#C60C30', name: 'Red',    pct: 33 }],
  'Chile':                    [{ hex: '#D52B1E', name: 'Red',    pct: 50 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }, { hex: '#003F87', name: 'Blue',   pct: 17 }],
  'China':                    [{ hex: '#DE2910', name: 'Red',    pct: 85 }, { hex: '#FFDE00', name: 'Yellow', pct: 15 }],
  'Colombia':                 [{ hex: '#FCD116', name: 'Yellow', pct: 50 }, { hex: '#003087', name: 'Blue',   pct: 25 }, { hex: '#CE1126', name: 'Red',    pct: 25 }],
  'Comoros':                  [{ hex: '#3A75C4', name: 'Blue',   pct: 50 }, { hex: '#3A9A2A', name: 'Green',  pct: 30 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }],
  'Democratic Republic of Congo': [{ hex: '#007FFF', name: 'Blue', pct: 70 }, { hex: '#F7D618', name: 'Yellow', pct: 15 }, { hex: '#CE1021', name: 'Red', pct: 15 }],
  'Republic of the Congo':    [{ hex: '#009543', name: 'Green',  pct: 33 }, { hex: '#FBDE4A', name: 'Yellow', pct: 34 }, { hex: '#DC241F', name: 'Red',    pct: 33 }],
  'Costa Rica':               [{ hex: '#002B7F', name: 'Blue',   pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 40 }, { hex: '#CE1126', name: 'Red',    pct: 20 }],
  'Croatia':                  [{ hex: '#FF0000', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#0000FF', name: 'Blue',   pct: 33 }],
  'Cuba':                     [{ hex: '#002A8F', name: 'Blue',   pct: 60 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }, { hex: '#CF142B', name: 'Red',    pct: 20 }],
  'Cyprus':                   [{ hex: '#FFFFFF', name: 'White',  pct: 80 }, { hex: '#D47600', name: 'Orange', pct: 15 }, { hex: '#4E7A3C', name: 'Green',  pct: 5  }],
  'Czech Republic':           [{ hex: '#002776', name: 'Blue',   pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 50 }, { hex: '#D7141A', name: 'Red',    pct: 17 }],
  'Denmark':                  [{ hex: '#C60C30', name: 'Red',    pct: 75 }, { hex: '#FFFFFF', name: 'White',  pct: 25 }],
  'Djibouti':                 [{ hex: '#6AB2E7', name: 'Blue',   pct: 50 }, { hex: '#12AD2B', name: 'Green',  pct: 45 }, { hex: '#FFFFFF', name: 'White',  pct: 5  }],
  'Dominican Republic':       [{ hex: '#002D62', name: 'Blue',   pct: 50 }, { hex: '#CF142B', name: 'Red',    pct: 45 }, { hex: '#FFFFFF', name: 'White',  pct: 5  }],
  'Ecuador':                  [{ hex: '#FFD100', name: 'Yellow', pct: 50 }, { hex: '#003893', name: 'Blue',   pct: 25 }, { hex: '#FF0000', name: 'Red',    pct: 25 }],
  'Egypt':                    [{ hex: '#CE1126', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'El Salvador':              [{ hex: '#0F47AF', name: 'Blue',   pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Equatorial Guinea':        [{ hex: '#3E9A00', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#E32118', name: 'Red',    pct: 33 }],
  'Eritrea':                  [{ hex: '#4189DD', name: 'Blue',   pct: 33 }, { hex: '#009A44', name: 'Green',  pct: 33 }, { hex: '#D52B1E', name: 'Red',    pct: 34 }],
  'Estonia':                  [{ hex: '#0072CE', name: 'Blue',   pct: 33 }, { hex: '#000000', name: 'Black',  pct: 34 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Eswatini':                 [{ hex: '#3E5EB9', name: 'Blue',   pct: 20 }, { hex: '#FFD900', name: 'Yellow', pct: 20 }, { hex: '#B10C0C', name: 'Red',    pct: 60 }],
  'Ethiopia':                 [{ hex: '#078930', name: 'Green',  pct: 33 }, { hex: '#FCDD09', name: 'Yellow', pct: 34 }, { hex: '#DA121A', name: 'Red',    pct: 33 }],
  'Fiji':                     [{ hex: '#68BFE5', name: 'Blue',   pct: 75 }, { hex: '#FFFFFF', name: 'White',  pct: 15 }, { hex: '#CC0001', name: 'Red',    pct: 10 }],
  'Finland':                  [{ hex: '#FFFFFF', name: 'White',  pct: 75 }, { hex: '#003580', name: 'Blue',   pct: 25 }],
  'France':                   [{ hex: '#002395', name: 'Blue',   pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#ED2939', name: 'Red',    pct: 33 }],
  'Gabon':                    [{ hex: '#009E60', name: 'Green',  pct: 33 }, { hex: '#FCD116', name: 'Yellow', pct: 34 }, { hex: '#3776AB', name: 'Blue',   pct: 33 }],
  'Gambia':                   [{ hex: '#3A7728', name: 'Green',  pct: 40 }, { hex: '#CE1126', name: 'Red',    pct: 40 }, { hex: '#0000FF', name: 'Blue',   pct: 15 }, { hex: '#FFFFFF', name: 'White', pct: 5 }],
  'Georgia':                  [{ hex: '#FFFFFF', name: 'White',  pct: 75 }, { hex: '#FF0000', name: 'Red',    pct: 25 }],
  'Germany':                  [{ hex: '#000000', name: 'Black',  pct: 33 }, { hex: '#DD0000', name: 'Red',    pct: 34 }, { hex: '#FFCE00', name: 'Yellow', pct: 33 }],
  'Ghana':                    [{ hex: '#006B3F', name: 'Green',  pct: 33 }, { hex: '#FCD116', name: 'Yellow', pct: 34 }, { hex: '#EF3340', name: 'Red',    pct: 33 }],
  'Greece':                   [{ hex: '#0D5EAF', name: 'Blue',   pct: 60 }, { hex: '#FFFFFF', name: 'White',  pct: 40 }],
  'Guatemala':                [{ hex: '#4997D0', name: 'Blue',   pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Guinea':                   [{ hex: '#CE1126', name: 'Red',    pct: 33 }, { hex: '#FCD116', name: 'Yellow', pct: 34 }, { hex: '#009460', name: 'Green',  pct: 33 }],
  'Honduras':                 [{ hex: '#0073CF', name: 'Blue',   pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Hungary':                  [{ hex: '#CE2939', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#477050', name: 'Green',  pct: 33 }],
  'Iceland':                  [{ hex: '#003897', name: 'Blue',   pct: 60 }, { hex: '#FFFFFF', name: 'White',  pct: 25 }, { hex: '#D72828', name: 'Red',    pct: 15 }],
  'India':                    [{ hex: '#FF9933', name: 'Orange', pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#138808', name: 'Green',  pct: 33 }],
  'Indonesia':                [{ hex: '#CE1126', name: 'Red',    pct: 50 }, { hex: '#FFFFFF', name: 'White',  pct: 50 }],
  'Iran':                     [{ hex: '#239F40', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#DA0000', name: 'Red',    pct: 33 }],
  'Iraq':                     [{ hex: '#CE1126', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'Ireland':                  [{ hex: '#169B62', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#FF883E', name: 'Orange', pct: 33 }],
  'Israel':                   [{ hex: '#FFFFFF', name: 'White',  pct: 75 }, { hex: '#0038B8', name: 'Blue',   pct: 25 }],
  'Italy':                    [{ hex: '#009246', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#CE2B37', name: 'Red',    pct: 33 }],
  'Ivory Coast':              [{ hex: '#F77F00', name: 'Orange', pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#009A44', name: 'Green',  pct: 33 }],
  'Jamaica':                  [{ hex: '#000000', name: 'Black',  pct: 40 }, { hex: '#FED100', name: 'Yellow', pct: 40 }, { hex: '#009B3A', name: 'Green',  pct: 20 }],
  'Japan':                    [{ hex: '#FFFFFF', name: 'White',  pct: 90 }, { hex: '#BC002D', name: 'Red',    pct: 10 }],
  'Jordan':                   [{ hex: '#007A3D', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#CE1126', name: 'Red',    pct: 33 }],
  'Kazakhstan':               [{ hex: '#00AFCA', name: 'Blue',   pct: 90 }, { hex: '#FEC50C', name: 'Yellow', pct: 10 }],
  'Kenya':                    [{ hex: '#006600', name: 'Green',  pct: 33 }, { hex: '#BB0000', name: 'Red',    pct: 34 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'Kosovo':                   [{ hex: '#244AA5', name: 'Blue',   pct: 80 }, { hex: '#E4AE3A', name: 'Gold',   pct: 20 }],
  'Kuwait':                   [{ hex: '#007A3D', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#CE1126', name: 'Red',    pct: 33 }],
  'Kyrgyzstan':               [{ hex: '#E8112D', name: 'Red',    pct: 90 }, { hex: '#FFFF00', name: 'Yellow', pct: 10 }],
  'Laos':                     [{ hex: '#CE1126', name: 'Red',    pct: 40 }, { hex: '#002868', name: 'Blue',   pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }],
  'Latvia':                   [{ hex: '#9E3039', name: 'Maroon', pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Lebanon':                  [{ hex: '#FFFFFF', name: 'White',  pct: 50 }, { hex: '#EE161F', name: 'Red',    pct: 40 }, { hex: '#00903B', name: 'Green',  pct: 10 }],
  'Lesotho':                  [{ hex: '#009A44', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#00209F', name: 'Blue',   pct: 33 }],
  'Liberia':                  [{ hex: '#BF0A30', name: 'Red',    pct: 60 }, { hex: '#FFFFFF', name: 'White',  pct: 35 }, { hex: '#002868', name: 'Blue',   pct: 5  }],
  'Libya':                    [{ hex: '#000000', name: 'Black',  pct: 50 }, { hex: '#239E46', name: 'Green',  pct: 40 }, { hex: '#E70013', name: 'Red',    pct: 10 }],
  'Liechtenstein':            [{ hex: '#002B7F', name: 'Blue',   pct: 50 }, { hex: '#CE1126', name: 'Red',    pct: 45 }, { hex: '#FFD700', name: 'Gold',   pct: 5  }],
  'Lithuania':                [{ hex: '#FDB913', name: 'Yellow', pct: 33 }, { hex: '#006A44', name: 'Green',  pct: 34 }, { hex: '#C1272D', name: 'Red',    pct: 33 }],
  'Luxembourg':               [{ hex: '#EF3340', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#00A3E0', name: 'Blue',   pct: 33 }],
  'Madagascar':               [{ hex: '#FFFFFF', name: 'White',  pct: 33 }, { hex: '#FC3D32', name: 'Red',    pct: 34 }, { hex: '#007E3A', name: 'Green',  pct: 33 }],
  'Malawi':                   [{ hex: '#000000', name: 'Black',  pct: 33 }, { hex: '#CE1126', name: 'Red',    pct: 34 }, { hex: '#339E35', name: 'Green',  pct: 33 }],
  'Malaysia':                 [{ hex: '#CC0001', name: 'Red',    pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 35 }, { hex: '#010094', name: 'Blue',   pct: 15 }, { hex: '#FFCC00', name: 'Yellow', pct: 10 }],
  'Maldives':                 [{ hex: '#D21034', name: 'Red',    pct: 60 }, { hex: '#007E3A', name: 'Green',  pct: 35 }, { hex: '#FFFFFF', name: 'White',  pct: 5  }],
  'Mali':                     [{ hex: '#14B53A', name: 'Green',  pct: 33 }, { hex: '#FCD116', name: 'Yellow', pct: 34 }, { hex: '#CE1126', name: 'Red',    pct: 33 }],
  'Malta':                    [{ hex: '#FFFFFF', name: 'White',  pct: 50 }, { hex: '#CF142B', name: 'Red',    pct: 50 }],
  'Mauritania':               [{ hex: '#006233', name: 'Green',  pct: 80 }, { hex: '#FFD700', name: 'Yellow', pct: 10 }, { hex: '#D01C1F', name: 'Red',    pct: 10 }],
  'Mauritius':                [{ hex: '#EA2839', name: 'Red',    pct: 25 }, { hex: '#1A206D', name: 'Blue',   pct: 25 }, { hex: '#FFD500', name: 'Yellow', pct: 25 }, { hex: '#00A551', name: 'Green', pct: 25 }],
  'Mexico':                   [{ hex: '#006847', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#CE1126', name: 'Red',    pct: 33 }],
  'Moldova':                  [{ hex: '#003DA5', name: 'Blue',   pct: 33 }, { hex: '#FFD200', name: 'Yellow', pct: 34 }, { hex: '#CC0001', name: 'Red',    pct: 33 }],
  'Mongolia':                 [{ hex: '#C4272F', name: 'Red',    pct: 67 }, { hex: '#015197', name: 'Blue',   pct: 28 }, { hex: '#F9CF02', name: 'Yellow', pct: 5  }],
  'Montenegro':               [{ hex: '#D4AF37', name: 'Gold',   pct: 75 }, { hex: '#D4101A', name: 'Red',    pct: 25 }],
  'Morocco':                  [{ hex: '#C1272D', name: 'Red',    pct: 90 }, { hex: '#006233', name: 'Green',  pct: 10 }],
  'Mozambique':               [{ hex: '#009A44', name: 'Green',  pct: 33 }, { hex: '#000000', name: 'Black',  pct: 15 }, { hex: '#FCE100', name: 'Yellow', pct: 20 }, { hex: '#D21034', name: 'Red', pct: 32 }],
  'Myanmar':                  [{ hex: '#FECB00', name: 'Yellow', pct: 33 }, { hex: '#34B233', name: 'Green',  pct: 34 }, { hex: '#EA2839', name: 'Red',    pct: 33 }],
  'Namibia':                  [{ hex: '#003580', name: 'Blue',   pct: 40 }, { hex: '#EF3340', name: 'Red',    pct: 40 }, { hex: '#009A44', name: 'Green',  pct: 15 }, { hex: '#FFFFFF', name: 'White', pct: 5 }],
  'Nepal':                    [{ hex: '#003893', name: 'Blue',   pct: 40 }, { hex: '#DC143C', name: 'Red',    pct: 60 }],
  'Netherlands':              [{ hex: '#AE1C28', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#21468B', name: 'Blue',   pct: 33 }],
  'New Zealand':              [{ hex: '#003087', name: 'Blue',   pct: 60 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }, { hex: '#CC142B', name: 'Red',    pct: 20 }],
  'Nicaragua':                [{ hex: '#3A75C4', name: 'Blue',   pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Niger':                    [{ hex: '#E05206', name: 'Orange', pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#0DB02B', name: 'Green',  pct: 33 }],
  'Nigeria':                  [{ hex: '#008751', name: 'Green',  pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'North Korea':              [{ hex: '#024FA2', name: 'Blue',   pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }, { hex: '#BE0000', name: 'Red',    pct: 50 }],
  'North Macedonia':          [{ hex: '#CE2028', name: 'Red',    pct: 70 }, { hex: '#F7E505', name: 'Yellow', pct: 30 }],
  'Norway':                   [{ hex: '#EF2B2D', name: 'Red',    pct: 70 }, { hex: '#FFFFFF', name: 'White',  pct: 18 }, { hex: '#002868', name: 'Blue',   pct: 12 }],
  'Oman':                     [{ hex: '#DB161B', name: 'Red',    pct: 50 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }, { hex: '#008000', name: 'Green',  pct: 17 }],
  'Pakistan':                 [{ hex: '#01411C', name: 'Green',  pct: 75 }, { hex: '#FFFFFF', name: 'White',  pct: 25 }],
  'Panama':                   [{ hex: '#FFFFFF', name: 'White',  pct: 50 }, { hex: '#005EB8', name: 'Blue',   pct: 30 }, { hex: '#D21034', name: 'Red',    pct: 20 }],
  'Papua New Guinea':         [{ hex: '#000000', name: 'Black',  pct: 50 }, { hex: '#CE1126', name: 'Red',    pct: 45 }, { hex: '#FCD116', name: 'Yellow', pct: 5  }],
  'Paraguay':                 [{ hex: '#D52B1E', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#0038A8', name: 'Blue',   pct: 33 }],
  'Peru':                     [{ hex: '#D91023', name: 'Red',    pct: 67 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Philippines':              [{ hex: '#0038A8', name: 'Blue',   pct: 40 }, { hex: '#CE1126', name: 'Red',    pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 15 }, { hex: '#FCD116', name: 'Yellow', pct: 5 }],
  'Poland':                   [{ hex: '#FFFFFF', name: 'White',  pct: 50 }, { hex: '#DC143C', name: 'Red',    pct: 50 }],
  'Portugal':                 [{ hex: '#006600', name: 'Green',  pct: 40 }, { hex: '#FF0000', name: 'Red',    pct: 60 }],
  'Qatar':                    [{ hex: '#8D1B3D', name: 'Maroon', pct: 75 }, { hex: '#FFFFFF', name: 'White',  pct: 25 }],
  'Romania':                  [{ hex: '#002B7F', name: 'Blue',   pct: 33 }, { hex: '#FCD116', name: 'Yellow', pct: 34 }, { hex: '#CE1126', name: 'Red',    pct: 33 }],
  'Russia':                   [{ hex: '#FFFFFF', name: 'White',  pct: 33 }, { hex: '#003580', name: 'Blue',   pct: 34 }, { hex: '#D52B1E', name: 'Red',    pct: 33 }],
  'Rwanda':                   [{ hex: '#20603D', name: 'Green',  pct: 33 }, { hex: '#FAD201', name: 'Yellow', pct: 34 }, { hex: '#20603D', name: 'Blue',   pct: 33 }],
  'Samoa':                    [{ hex: '#CE1126', name: 'Red',    pct: 75 }, { hex: '#002B7F', name: 'Blue',   pct: 20 }, { hex: '#FFFFFF', name: 'White',  pct: 5  }],
  'Sao Tome and Principe':    [{ hex: '#12AD2B', name: 'Green',  pct: 50 }, { hex: '#FFCE00', name: 'Yellow', pct: 35 }, { hex: '#D21034', name: 'Red',    pct: 15 }],
  'Saudi Arabia':             [{ hex: '#006C35', name: 'Green',  pct: 90 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }],
  'Senegal':                  [{ hex: '#00853F', name: 'Green',  pct: 33 }, { hex: '#FDEF42', name: 'Yellow', pct: 34 }, { hex: '#E31B23', name: 'Red',    pct: 33 }],
  'Serbia':                   [{ hex: '#C6363C', name: 'Red',    pct: 33 }, { hex: '#0C4076', name: 'Blue',   pct: 34 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }],
  'Sierra Leone':             [{ hex: '#1EB53A', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#0072C6', name: 'Blue',   pct: 33 }],
  'Slovakia':                 [{ hex: '#FFFFFF', name: 'White',  pct: 33 }, { hex: '#0B4EA2', name: 'Blue',   pct: 34 }, { hex: '#EE1C25', name: 'Red',    pct: 33 }],
  'Slovenia':                 [{ hex: '#003DA5', name: 'Blue',   pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#EF3340', name: 'Red',    pct: 33 }],
  'Somalia':                  [{ hex: '#4189DD', name: 'Blue',   pct: 90 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }],
  'South Africa':             [{ hex: '#007A4D', name: 'Green',  pct: 30 }, { hex: '#FFB81C', name: 'Yellow', pct: 20 }, { hex: '#DE3831', name: 'Red',    pct: 20 }, { hex: '#000000', name: 'Black', pct: 15 }],
  'South Korea':              [{ hex: '#FFFFFF', name: 'White',  pct: 70 }, { hex: '#CD2E3A', name: 'Red',    pct: 10 }, { hex: '#0047A0', name: 'Blue',   pct: 10 }, { hex: '#000000', name: 'Black', pct: 10 }],
  'South Sudan':              [{ hex: '#078930', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }, { hex: '#D21034', name: 'Red',    pct: 33 }, { hex: '#000000', name: 'Black', pct: 24 }],
  'Spain':                    [{ hex: '#AA151B', name: 'Red',    pct: 67 }, { hex: '#F1BF00', name: 'Yellow', pct: 33 }],
  'Sri Lanka':                [{ hex: '#8D153A', name: 'Maroon', pct: 60 }, { hex: '#FFC832', name: 'Yellow', pct: 20 }, { hex: '#009A44', name: 'Green',  pct: 10 }, { hex: '#FF671F', name: 'Orange', pct: 10 }],
  'Sudan':                    [{ hex: '#D21034', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'Suriname':                 [{ hex: '#377E3F', name: 'Green',  pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }, { hex: '#B40A2D', name: 'Red',    pct: 30 }, { hex: '#ECC81D', name: 'Yellow', pct: 10 }],
  'Sweden':                   [{ hex: '#006AA7', name: 'Blue',   pct: 75 }, { hex: '#FECC02', name: 'Yellow', pct: 25 }],
  'Switzerland':              [{ hex: '#FF0000', name: 'Red',    pct: 80 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }],
  'Syria':                    [{ hex: '#CE1126', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'Taiwan':                   [{ hex: '#FE0000', name: 'Red',    pct: 75 }, { hex: '#000095', name: 'Blue',   pct: 20 }, { hex: '#FFFFFF', name: 'White',  pct: 5  }],
  'Tajikistan':               [{ hex: '#CC0000', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#009A44', name: 'Green',  pct: 33 }],
  'Tanzania':                 [{ hex: '#1EB53A', name: 'Green',  pct: 33 }, { hex: '#000000', name: 'Black',  pct: 33 }, { hex: '#009FCA', name: 'Blue',   pct: 33 }],
  'Thailand':                 [{ hex: '#A51931', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#2D2A4A', name: 'Blue',   pct: 33 }],
  'Timor-Leste':              [{ hex: '#DC241F', name: 'Red',    pct: 70 }, { hex: '#000000', name: 'Black',  pct: 20 }, { hex: '#FFC726', name: 'Yellow', pct: 10 }],
  'Togo':                     [{ hex: '#006A4E', name: 'Green',  pct: 50 }, { hex: '#FFCE00', name: 'Yellow', pct: 30 }, { hex: '#D21034', name: 'Red',    pct: 20 }],
  'Tonga':                    [{ hex: '#C10000', name: 'Red',    pct: 75 }, { hex: '#FFFFFF', name: 'White',  pct: 25 }],
  'Trinidad and Tobago':      [{ hex: '#CE1126', name: 'Red',    pct: 75 }, { hex: '#000000', name: 'Black',  pct: 15 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }],
  'Tunisia':                  [{ hex: '#E70013', name: 'Red',    pct: 80 }, { hex: '#FFFFFF', name: 'White',  pct: 20 }],
  'Turkey':                   [{ hex: '#E30A17', name: 'Red',    pct: 90 }, { hex: '#FFFFFF', name: 'White',  pct: 10 }],
  'Turkmenistan':             [{ hex: '#1B9B4F', name: 'Green',  pct: 85 }, { hex: '#CF1020', name: 'Red',    pct: 15 }],
  'Uganda':                   [{ hex: '#000000', name: 'Black',  pct: 33 }, { hex: '#FCD116', name: 'Yellow', pct: 34 }, { hex: '#D90000', name: 'Red',    pct: 33 }],
  'Ukraine':                  [{ hex: '#005BBB', name: 'Blue',   pct: 50 }, { hex: '#FFD500', name: 'Yellow', pct: 50 }],
  'United Arab Emirates':     [{ hex: '#009A44', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'United Kingdom':           [{ hex: '#CF142B', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 33 }, { hex: '#012169', name: 'Blue',   pct: 34 }],
  'United States':            [{ hex: '#B22234', name: 'Red',    pct: 40 }, { hex: '#FFFFFF', name: 'White',  pct: 40 }, { hex: '#3C3B6E', name: 'Blue',   pct: 20 }],
  'Uruguay':                  [{ hex: '#FFFFFF', name: 'White',  pct: 70 }, { hex: '#5EB6E4', name: 'Blue',   pct: 25 }, { hex: '#FCD116', name: 'Yellow', pct: 5  }],
  'Uzbekistan':               [{ hex: '#1EB53A', name: 'Green',  pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 15 }, { hex: '#009FCA', name: 'Blue',   pct: 52 }],
  'Vanuatu':                  [{ hex: '#009543', name: 'Green',  pct: 40 }, { hex: '#D21034', name: 'Red',    pct: 40 }, { hex: '#000000', name: 'Black',  pct: 15 }, { hex: '#FDCE12', name: 'Yellow', pct: 5 }],
  'Venezuela':                [{ hex: '#CF142B', name: 'Red',    pct: 33 }, { hex: '#FFD700', name: 'Yellow', pct: 34 }, { hex: '#00247D', name: 'Blue',   pct: 33 }],
  'Vietnam':                  [{ hex: '#DA251D', name: 'Red',    pct: 90 }, { hex: '#FFFF00', name: 'Yellow', pct: 10 }],
  'Yemen':                    [{ hex: '#CE1126', name: 'Red',    pct: 33 }, { hex: '#FFFFFF', name: 'White',  pct: 34 }, { hex: '#000000', name: 'Black',  pct: 33 }],
  'Zambia':                   [{ hex: '#198A00', name: 'Green',  pct: 75 }, { hex: '#EF7D00', name: 'Orange', pct: 15 }, { hex: '#000000', name: 'Black',  pct: 10 }],
  'Zimbabwe':                 [{ hex: '#006400', name: 'Green',  pct: 33 }, { hex: '#FFD200', name: 'Yellow', pct: 20 }, { hex: '#D21034', name: 'Red',    pct: 33 }, { hex: '#000000', name: 'Black', pct: 14 }],
}
