// 2024 populations (in millions) from World Bank data, keyed by exact game NAME values
export const POPULATION = {
  // Africa
  'Algeria':                           46.8,
  'Angola':                            37.9,
  'Benin':                             14.5,
  'Botswana':                           2.52,
  'Burkina Faso':                      23.5,
  'Burundi':                           14.0,
  'Cabo Verde':                         0.525,
  'Cameroon':                          29.1,
  'Central African Republic':           5.33,
  'Chad':                              20.3,
  'Comoros':                            0.867,
  'Congo':                              6.33,
  'Democratic Republic of Congo':     109.3,
  'Djibouti':                           1.17,
  'Egypt':                            116.5,
  'Equatorial Guinea':                  1.89,
  'Eritrea':                            3.54,
  'Eswatini':                           1.24,
  'Ethiopia':                         132.1,
  'Gabon':                              2.54,
  'Gambia':                             2.76,
  'Ghana':                             34.4,
  'Guinea':                            14.8,
  'Guinea-Bissau':                      2.20,
  'Ivory Coast':                       31.9,
  'Kenya':                             56.4,
  'Lesotho':                            2.34,
  'Liberia':                            5.61,
  'Libya':                              7.38,
  'Madagascar':                        32.0,
  'Malawi':                            21.7,
  'Mali':                              24.5,
  'Mauritania':                         5.17,
  'Mauritius':                          1.25,
  'Morocco':                           38.1,
  'Mozambique':                        34.6,
  'Namibia':                            3.03,
  'Niger':                             27.0,
  'Nigeria':                          232.7,
  'Rwanda':                            14.3,
  'Sao Tome and Principe':              0.236,
  'Senegal':                           18.5,
  'Seychelles':                         0.121,
  'Sierra Leone':                       8.64,
  'Somalia':                           19.0,
  'South Africa':                      64.0,
  'South Sudan':                       11.9,
  'Sudan':                             50.4,
  'Tanzania':                          68.6,
  'Togo':                               9.52,
  'Tunisia':                           12.3,
  'Uganda':                            50.0,
  'Zambia':                            21.3,
  'Zimbabwe':                          16.6,

  // Americas
  'Antigua and Barbuda':                0.094,
  'Argentina':                         45.7,
  'Bahamas':                            0.401,
  'Barbados':                           0.282,
  'Belize':                             0.417,
  'Bolivia':                           12.4,
  'Brazil':                           212.0,
  'Canada':                            41.3,
  'Chile':                             19.8,
  'Colombia':                          52.9,
  'Costa Rica':                         5.13,
  'Cuba':                              11.0,
  'Dominica':                           0.066,
  'Dominican Republic':                11.4,
  'Ecuador':                           18.1,
  'El Salvador':                        6.34,
  'Grenada':                            0.117,
  'Guatemala':                         18.4,
  'Guyana':                             0.831,
  'Haiti':                             11.8,
  'Honduras':                          10.8,
  'Jamaica':                            2.84,
  'Mexico':                           130.9,
  'Nicaragua':                          6.92,
  'Panama':                             4.52,
  'Paraguay':                           6.93,
  'Peru':                              34.2,
  'Saint Kitts and Nevis':              0.047,
  'Saint Lucia':                        0.180,
  'Saint Vincent and the Grenadines':   0.101,
  'Suriname':                           0.634,
  'Trinidad and Tobago':                1.37,
  'United States of America':         340.1,
  'Uruguay':                            3.39,
  'Venezuela':                         28.4,

  // Asia
  'Afghanistan':                       42.6,
  'Armenia':                            3.03,
  'Azerbaijan':                        10.2,
  'Bahrain':                            1.59,
  'Bangladesh':                       173.6,
  'Bhutan':                             0.792,
  'Brunei':                             0.463,
  'Cambodia':                          17.6,
  'China':                           1409.0,
  'Cyprus':                             1.36,
  'Georgia':                            3.70,
  'India':                           1450.9,
  'Indonesia':                        283.5,
  'Iran':                              91.6,
  'Iraq':                              46.0,
  'Israel':                             9.97,
  'Japan':                            124.0,
  'Jordan':                            11.6,
  'Kazakhstan':                        20.6,
  'Kuwait':                             4.90,
  'Kyrgyzstan':                         7.22,
  'Laos':                               7.77,
  'Lebanon':                            5.81,
  'Malaysia':                          35.6,
  'Maldives':                           0.528,
  'Mongolia':                           3.52,
  'Myanmar':                           54.5,
  'Nepal':                             29.7,
  'North Korea':                       26.5,
  'Oman':                               5.28,
  'Pakistan':                         251.3,
  'Palestine':                          5.29,
  'Philippines':                      115.8,
  'Qatar':                              2.86,
  'Saudi Arabia':                      35.3,
  'Singapore':                          6.04,
  'South Korea':                       51.8,
  'Sri Lanka':                         21.9,
  'Syria':                             24.7,
  'Taiwan':                            23.0,
  'Tajikistan':                        10.6,
  'Thailand':                          71.7,
  'Timor-Leste':                        1.40,
  'Turkey':                            85.5,
  'Turkmenistan':                       7.49,
  'United Arab Emirates':              11.0,
  'Uzbekistan':                        36.4,
  'Vietnam':                          101.0,
  'Yemen':                             40.6,

  // Europe
  'Albania':                            2.38,
  'Andorra':                            0.082,
  'Austria':                            9.18,
  'Belarus':                            9.13,
  'Belgium':                           11.9,
  'Bosnia and Herzegovina':             3.16,
  'Bulgaria':                           6.44,
  'Croatia':                            3.87,
  'Czech Republic':                    10.9,
  'Denmark':                            5.98,
  'Estonia':                            1.37,
  'Finland':                            5.62,
  'France':                            68.6,
  'Germany':                           83.5,
  'Greece':                            10.4,
  'Hungary':                            9.56,
  'Iceland':                            0.387,
  'Ireland':                            5.40,
  'Italy':                             59.0,
  'Kosovo':                             1.59,
  'Latvia':                             1.87,
  'Liechtenstein':                      0.040,
  'Lithuania':                          2.89,
  'Luxembourg':                         0.677,
  'Malta':                              0.569,
  'Moldova':                            2.40,
  'Monaco':                             0.039,
  'Montenegro':                         0.624,
  'Netherlands':                       18.0,
  'North Macedonia':                    1.82,
  'Norway':                             5.57,
  'Poland':                            36.6,
  'Portugal':                          10.7,
  'Romania':                           19.1,
  'Russia':                           143.5,
  'San Marino':                         0.034,
  'Serbia':                             6.59,
  'Slovakia':                           5.42,
  'Slovenia':                           2.13,
  'Spain':                             48.8,
  'Sweden':                            10.6,
  'Switzerland':                        9.01,
  'Ukraine':                           37.9,
  'United Kingdom':                    69.2,
  'Vatican':                            0.0008,

  // Oceania
  'Australia':                         27.2,
  'Fiji':                               0.929,
  'Kiribati':                           0.135,
  'Marshall Islands':                   0.038,
  'Federated States of Micronesia':     0.113,
  'Nauru':                              0.012,
  'New Zealand':                        5.29,
  'Palau':                              0.018,
  'Papua New Guinea':                  10.6,
  'Samoa':                              0.218,
  'Solomon Islands':                    0.819,
  'Tonga':                              0.104,
  'Tuvalu':                             0.010,
  'Vanuatu':                            0.328,
}

export function getPopulation(name) {
  return POPULATION[name] ?? null
}
